### ISSUE TITLE
[Question] Does this allow user to Merge Android app backup with desktop chats?

### ISSUE THREAD

**Issue by pixincreate** [bepaald/signalbackup-tools#101]
As the title says, does this allows a user to merge the android app backup with desktop synced chats? 
I've been using Signal on desktop while it's not yet installed on my phone. Last backup that I've on Android is of Feb 24 and all the chats do exist on PC. I want to merge both of them. Does this tool allows me to achieve the goal?

Thanks!

**Comment by bepaald** [comment]
It allows* to import messages from the Desktop into the Android backup, not the other way around.

\* Though there are also still a few issues, especially for older Desktop databases which are being tracked here #57 and here #94.

**Comment by pixincreate** [comment]
So it does allow me to merge the latest (today) chats from desktop to Android backup (24/02/2023 backup), right?

**Comment by pixincreate** [comment]
Cool, that did the job! Although a few messages got corrupted I got all of my other messages flawlessly! 
Thanks!

**Comment by bepaald** [comment]
Glad to hear it (mostly) worked. I am a little curious what kind of corruption you are seeing, maybe you could describe it?

Thanks!

**Comment by pixincreate** [comment]
I think the latest one, has fixed that, not sure. Some of the data straight away said that they cannot be restored.  
I attached the logs of the latest one here: 

[logs.txt](https://github.com/bepaald/signalbackup-tools/files/10953593/logs.txt)

**Comment by bepaald** [comment]
Yeah, not all message types are supported yet. Some will be in the future, but probably not all of them. Thanks for the feedback!

**Comment by pixincreate** [comment]
Cool. Thanks for this amazing project btw!
