### ISSUE TITLE
Molly (Signal Fork) version v6.11.7-1-FOSS crashes when i try to restore encrypted backup file

### ISSUE THREAD

**Issue by straightshark** [bepaald/signalbackup-tools#103]
I opened this issue as per your suggestion to open it on your Github and feel free to ask me when to delete this issue when we solve it.

Molly is a FOSS fork of signal. 
https://molly.im/
Molly crashes and takes me back to home screen when I try to restore the Encrypted Backup file which I properly copied to my pc before completely resetting my phone.
The app does accept my passphrase but It crashes right after this message "800 messages so far".
The backup file is of 567MB which is not that big when compared to other people who have had this issue.
I also verified my Backup passphrase in the app before resetting the phone completely.
I did a reset because I wanted a clean start with my phone again.
I backed my file 2 days ago and tried to restore it today and both times I had the same version of Molly (v6.11.7-1-FOSS)

Steps to reproduce
1. Open Molly > Settings > Chats > Enable Chat back up
2. Assign a folder where the backup will be stored
3. Create the Encrypted backup
4. Save the backup passphrase
5. Verify the backup passphrase via the Verify option
6. Copy the Encrypted file in laptop
7. Reset the phone
8. Copy the Encrypted backup file back from laptop to phone
9. Download Molly
10. Go to Restore Account
11. Select Restore via Backup file
12. Select the encrypted backup file from the phone
13. Input the backup passphrase

Molly version
v6.11.7-1-FOSS

Android version
Android 13

Device
Pixel 6

**Comment by straightshark** [comment]
I tried to download your tool as per your instructions but in downloads folder of my browser it shows  " Failed - Virus Detected " and then Windows Defender Antivirus Shows that it found threats. It shows that your signalbackup-tool.exe has Trojan Horse : Win32/Wacatac.B!ml

![Imagepipe_1](https://user-images.githubusercontent.com/128378580/226503182-6ac69731-c7e3-49a3-bd85-9e19556281b9.jpg)

**Comment by bepaald** [comment]
Well, I've never heard _that_ before. As long as you got the file from this page it is surely a false positive. Just to see if any other virus scanners detect anything in this executable, I just uploaded the program to [virustotal](https://www.virustotal.com/gui/home/upload) and got this:


![Screenshot 2023-03-21 at 06-42-21 VirusTotal - File - 972cac9ff1a98114798a5acf281163f5b3a3b2af58277c9c00e4910715737189](https://user-images.githubusercontent.com/38437099/226535228-dd37b4bc-7e7d-46a4-824e-8e6efa46f25f.png)
Feel free to do the same to be sure. I also let Kaspersky scan the file: [here are the results](https://opentip.kaspersky.com/972CAC9FF1A98114798A5ACF281163F5B3A3B2AF58277C9C00E4910715737189/results?tab=upload).

I'm not that familiar with Windows, I don't ever use it, but I assume under 'Actions' in that screenshot, you can tell Windows Defender to ignore the 'threat'. If you do not feel comfortable doing that, I'm not sure what to do. You could always run the program in a virtual machine and/or compile yourself under Linux, but as you say you are not good with computers I don't think these things are feasible.

**Comment by straightshark** [comment]
I used your tool and got this as output

WARNING Foreign key constraint violated.
--------------------------
| table | parent  | fkid |
--------------------------
| call  | message | 1    |
--------------------------
Checking foreign key constraints...
ERROR Foreign key constraint violated. This will not end well, aborting.
      Please report this error to the program author.
--------------------------
| table | parent  | fkid |
--------------------------
| call  | message | 1    |
--------------------------

**Comment by bepaald** [comment]
Ok, now run

```
signalbackup-tools [input] [passphrase] --runsqlquery "DELETE FROM call WHERE message_id NOT IN (SELECT _id FROM message)" -o [new_backup_file]
```

Assert there are no errors being printed (I don't expect any) and try to restore the `new_backup_file`. Make sure the filename is one that Signal (or Molly) will recognize. For Signal, it has to be `signal-YYYY-mm-dd-HH-MM-SS.backup` (where the date needs to be the newest available to restore to the program).

**Comment by straightshark** [comment]
I did exactly what you said and the new backup file works perfectly. 
Thanks a lot for your help!! 
And I hope signal and molly developers rectify the issue.
