### ISSUE TITLE
Export to HTML support for older database

### ISSUE THREAD

**Issue by AennchenVonRadau** [bepaald/signalbackup-tools#106]
I'm really happy about HTML export, thank you so much for adding this feature! How are the chances that older database versions will be supported in the future? I have a backup with database version 167 (so close!), from an old Android device on which I unfortunately cannot install any more updates.

**Comment by bepaald** [comment]
I was not looking forward to this, as right before v168  the database was quite a bit more complex. Especially when trying to support _both_ database formats at the same time.

But then I figured, why not just try to upgrade the input database version, if that works, all other code can stay the same. So I've now attempted that. If you get the latest version, you should see `Attempting to migrate database from version 167 to version 170...` and if all goes well, it will hopefully do the export after that.

Please let me know if it works.

**Comment by AennchenVonRadau** [comment]
Yes, it's working! That's great, thank you so much :)
