### ISSUE TITLE
HTML Export Failed

### ISSUE THREAD

**Issue by RetroJimmyX** [bepaald/signalbackup-tools#113]
Thanks for this project! While --output --mediadump functins work, I had an issue with --exporthtml

My datbase was exported from Signal on the 26th April so I guess would be a recent verion. The error I experienced is:

```
Reading backup file...
FRAME 8564 (100.0%)... Read entire backup file...

done!
Dealing with thread 1
Getting value of field 'recipient_device_id' (idx 1). Value as string:
Type: Dn Requested type: x
terminate called after throwing an instance of 'std::bad_any_cast'
  what():  bad any_cast
```

Hope you can help me or this helps the developer. Thanks again.

**Comment by bepaald** [comment]
Thanks for reporting! I see I made a stupid typo in my commit yesterday. I'm not at home at this moment, but this will be fixed in a few hours. Thanks again!

**Comment by RetroJimmyX** [comment]
Hey thanks for prompt response, closing issue.
_I'm not a programmer (some hobbyist Python) but I presume it was just something to do with types and casting._

**Comment by RetroJimmyX** [comment]
Hey thanks for prompt response, closing issue.
_I'm not a programmer (some hobbyist Python) but I presume it was just something to do with types and casting._

**Comment by RetroJimmyX** [comment]
Downloaded and tested as working, thanks.
