### ISSUE TITLE
run exe on windows

### ISSUE THREAD

**Issue by 3Ryan3** [bepaald/signalbackup-tools#125]
Hi,

sorry to bother but I can't get the windows file to decrypt my backup and don't have the programming skills to understand all the readme Details.

I tried to run the backup with the exe (open with and manually select the exe file). Commands are running but I don't get any file output.

With older tools (which are from 2018 and no longer working) I had to add a certain command in the command line to get the exe to export a file (eg signal-back_windows.exe format -f csv -o backup.csv signal-XXX.backup)

I want to export the backup to csv. Would anyone be so kind and tell me how to do this on windows. eg. in the command window

thx
Ryan

**Comment by 3Ryan3** [comment]
OK, managed to do after some try an error to export to csv 
signalbackup-tools_win.exe signal-20xx-xx-xx-xx-xx-xx.backup passfrase --exportcsv message=messages.csv

my "new" issue ist, that it is separated by comma. I also do have commas in my messages. so that gets messy. any way to export with a different separator?
and/or to export only one communication with one person? Would also make it easier

**Comment by 3Ryan3** [comment]
tried xml and it returned an error
![2023-06-15_09h31_36](https://github.com/bepaald/signalbackup-tools/assets/136228214/f1ecac03-7250-4423-bf24-8b5580d77544)

**Comment by bepaald** [comment]
I think this is solved then? Feel free to re-open or open a new issue if you feel it necessary.
