### ISSUE TITLE
Help on retrieving backup from MacOS Ventura

### ISSUE THREAD

**Issue by Andrewbestman** [bepaald/signalbackup-tools#126]
I recently got my iPhone wiped and I only have some of my chat history in my Mac Signal Desktop. After typing the first line of code, this is what I got:
andrew@Andrews-Air-2 ~ % brew install --HEAD /Users/andrew/Downloads/signalbackup-tools_win.exe
Running `brew update --auto-update`...
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Downloading https://formulae.brew.sh/api/formula.jws.json
########################################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
########################################################################################## 100.0%
Error: signalbackup-tools_win.exe: /users/andrew/downloads/signalbackup-tools_win.exe:1: invalid multibyte char (UTF-8)

What should I do next and can I get the backup back on my iPhone?

**Comment by bepaald** [comment]
You appear to have downloaded the Windows version of the program, and trying to install it as if it were a homebrew package. This will not work of course. Please read the README carefully: [https://github.com/bepaald/signalbackup-tools#macos](https://github.com/bepaald/signalbackup-tools#macos). You need to get the `signalbackup-tools.rb` file from this repo (or just clone the entire repo and put that file after `brew install --head`. But, read ahead:

>What should I do next and can I get the backup back on my iPhone?

Unfortunately, I don't think it is possible to get you messages back. Signal on iOS does not support backup files (which is what this program works with, hence its name). So, unless I'm misunderstanding your situation, I'm afraid this program is not for you.

This program would read the messages form your Desktop app, and import them into a backup (which you don't have). Afterwards, the backup with the imported messages could be restored by Signal Android (but not on iPhone). There are long threads about backup support on iOS, but I don't closely follow them. In the past, Apple made it impossible to create backups (in the way Signal would want), but I'm not sure if that is still the case today. The main community discussion (with at least some responses from the developers) is here: https://community.signalusers.org/t/ios-backup-keeping-message-history-when-switching-phones/1736/1

Sorry for your loss. Please let me know if you have any questions or if you believe I can help you in any some way. Otherwise, feel free to close this issue.

**Comment by Andrewbestman** [comment]
https://raw.githubusercontent.com/bepaald/signalbackup-tools/master/homebrew/signalbackup-tools.rb

andrew@Andrews-Air-2 ~ % % brew install --HEAD class SignalbackupTools < Formula
  desc "A tool to work with Signal backup files"
  homepage "https://github.com/bepaald/signalbackup-tools"
  license "GPL-3.0-or-later"
  head "https://github.com/bepaald/signalbackup-tools.git", branch: "master"

  depends_on "cmake" =>:build
  depends_on "openssl@3"
  depends_on "sqlite"

  def install
    system "cmake", "-B", "build", *std_cmake_args
    system "cmake", "--build", "build", "-j"
    bin.install "build/signalbackup-tools"
  end

  test do
    # not a 'good' test, but not sure what else is possible here
    `#{bin}/signalbackup-tools --help`
    result=$?.success?
    return result
  end
end

zsh: parse error near `end'

Is there anything I've done wrong here?

**Comment by Andrewbestman** [comment]
I've used brew create to grab the url, and used brew install --HEAD [path/to/signalbackup-tools.rb].
Is there any version number? 

andrew@Andrews-Air-2 ~ % brew install --HEAD /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/signalbackup-tools.rb
Error: invalid attribute for formula 'signalbackup-tools': version (nil)
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:297:in `validate_attributes!'
/opt/homebrew/Library/Homebrew/formula.rb:222:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:437:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:437:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:716:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:643:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:315:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
andrew@Andrews-Air-2 ~ %

**Comment by bepaald** [comment]
I must admit that I have very little experience with macOs, and even less with homebrew. But here is what I do, and what should be working.

Get the formula (there are other ways than cloning the entire repo, but I did this):
```
bepaald@Bass-MacBook-Pro ~ % git clone https://github.com/bepaald/signalbackup-tools
Cloning into 'signalbackup-tools'...
remote: Enumerating objects: 5100, done.
remote: Counting objects: 100% (1618/1618), done.
remote: Compressing objects: 100% (383/383), done.
remote: Total 5100 (delta 1265), reused 1553 (delta 1206), pack-reused 3482
Receiving objects: 100% (5100/5100), 1.46 MiB | 16.28 MiB/s, done.
Resolving deltas: 100% (4017/4017), done.
```

Install with brew:
```
bepaald@Bass-MacBook-Pro ~ % brew install --HEAD ./signalbackup-tools/homebrew/signalbackup-tools.rb 
Error: Failed to load cask: ./signalbackup-tools/homebrew/signalbackup-tools.rb
Cask 'signalbackup-tools' is unreadable: wrong constant name #<Class:0x00007fc0a349d570>
Warning: Treating ./signalbackup-tools/homebrew/signalbackup-tools.rb as a formula.
==> Fetching signalbackup-tools
==> Cloning https://github.com/bepaald/signalbackup-tools.git
Updating /Users/bepaald/Library/Caches/Homebrew/signalbackup-tools--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at c98fbb0 Update readme
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.2.

==> cmake -B build
==> cmake --build build -j
==> Downloading https://formulae.brew.sh/api/cask.jws.json
##################################################################################################################################################################################### 100.0%
🍺  /usr/local/Cellar/signalbackup-tools/HEAD-c98fbb0: 5 files, 2.2MB, built in 55 seconds
==> Running `brew cleanup signalbackup-tools`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> `brew cleanup` has not been run in the last 30 days, running now...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /usr/local/Cellar/ca-certificates/2023-01-10... (3 files, 216.9KB)
Removing: /Users/bepaald/Library/Caches/Homebrew/ca-certificates--2023-01-10... (122.6KB)
Removing: /usr/local/Cellar/cmake/3.26.3... (3,188 files, 49.8MB)
Removing: /Users/bepaald/Library/Caches/Homebrew/cmake--3.26.3... (16.4MB)
Removing: /Users/bepaald/Library/Caches/Homebrew/libnghttp2--1.52.0... (210.0KB)
Removing: /Users/bepaald/Library/Caches/Homebrew/nettle--3.8.1... (968.4KB)
Removing: /Users/bepaald/Library/Caches/Homebrew/openssl@1.1--1.1.1t... (5.4MB)
Removing: /usr/local/Cellar/openssl@3/3.1.0... (6,494 files, 29.9MB)
Removing: /Users/bepaald/Library/Caches/Homebrew/openssl@3--3.1.0... (7.9MB)
Removing: /usr/local/Cellar/sqlite/3.41.2... (11 files, 4.4MB)
Removing: /Users/bepaald/Library/Caches/Homebrew/sqlite--3.41.2... (2.1MB)
Removing: /Users/bepaald/Library/Logs/Homebrew/wget... (64B)
Removing: /Users/bepaald/Library/Logs/Homebrew/cmake... (64B)
Removing: /Users/bepaald/Library/Logs/Homebrew/sqlite... (64B)
Removing: /Users/bepaald/Library/Logs/Homebrew/openssl@3... (64B)
Pruned 0 symbolic links and 2 directories from /usr/local
```

Done!
```
bepaald@Bass-MacBook-Pro ~ % signalbackup-tools  
signalbackup-tools (signalbackup-tools) source version 20230615.142014 (OpenSSL)
```

**Comment by bepaald** [comment]
I assume we're done here. Please let me know if there's anything more I can do for you.
