### ISSUE TITLE
#include <numbers> fatal error

### ISSUE THREAD

**Issue by Gajusbonus** [bepaald/signalbackup-tools#129]
Error compiling.
missing a file.
This is the output of "sh BUILDSCRIPT.sh" 
BUILDING (49/140): /usr/bin/g++ -c -Wall -Wextra -Wshadow -Wold-style-cast -Woverloaded-virtual -pedantic -std=c++2a -O3 -march=native -flto  -o "signalbackup/o/getcustomcolor.o" "signalbackup/getcustomcolor.cc"
signalbackup/getcustomcolor.cc:23:10: fatal error: numbers: No such file or directory
   23 | #include numbers
      |          ^~~~~~~~~
compilation terminated.

**Comment by bepaald** [comment]
Ok, I see the `numbers` header was only added to the standard library in C++20. I did not know that. C++20 should however be pretty well supported and you are passing the `-std=c++2a` flag.

I will get this fixed, but do you mind telling me what compiler version you are running?

**Comment by bepaald** [comment]
I actually already _almost_ accounted for the math constants not being available, just missed one `#ifdef` (I hope). Try it now please.

**Comment by Gajusbonus** [comment]
the -std=c++2a flag did not work, same error.
 I also tried -std=gnu++2a without result.
BUILDING (49/140): /usr/bin/g++ -c -Wall -Wextra -Wshadow -Wold-style-cast -Woverloaded-virtual -pedantic -std=c++2a -O3 -march=native -flto -std=gnu++2a -o "signalbackup/o/getcustomcolor.o" "signalbackup/getcustomcolor.cc"
signalbackup/getcustomcolor.cc:23:10: fatal error: numbers: No such file or directory
   23 | #include numbers
      |          ^~~~~~~~~
I'm using gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by Gajusbonus** [comment]
Yes, I pulled in the last commit.
now it compiles.
Previous answer I had just modified BUILDSCRIPT.sh and added the flag.
