### ISSUE TITLE
Export to IRC style chat logs

### ISSUE THREAD

**Issue by flux77** [bepaald/signalbackup-tools#130]
Please implement export to plain text IRC-style chat logs. WhatsApp chat exports have a similar format. For example:

```
[2023-07-10 01:23] <alice> Where are you?
[2023-07-10 01:25] <bob> I'm at the beach.
[2023-07-10 01:26] *** <bob> sent "Signal-1.jpeg"
[2023-07-10 01:27] <alice> Come home. You haven't washed the dishes.
```

**Comment by bepaald** [comment]
Is there any more to it than that? Is "IRC-style" some well defined standard, or just anything that looks somewhat like that? I assume this means attachments (the actual attachment data) are excluded from the export, as are emoji-reactions and quotes?

I've very quickly copy pasted something together, give it a try and let me know if it's what you're looking for. It probably only works (if at all) on (near) current backups, but I've hardly tested it.

**Comment by bepaald** [comment]
No worries if you're busy, but were you planning on testing this? If not, I'd like to close this issue. Thanks!

**Comment by johannesnagl** [comment]
can we somehow get this feature through brew? would love to test it. also, would be great if `exporttxt` would also take the reactions of a message into consideration, eg:

```
[2023-07-10 01:27] <alice> Come home. You haven't washed the dishes. (Bob: 😮)
```

**Comment by bepaald** [comment]
> can we somehow get this feature through brew? would love to test it. 

Not sure what you mean, the feature is simply present in the current version and documented in the readme. If you just install (through brew or any other way) it should be there. Is something not working?

> also, would be great if `exporttxt` would also take the reactions of a message into consideration, eg:
> 
> ```
> [2023-07-10 01:27] <alice> Come home. You haven't washed the dishes. (Bob: 😮)
> ```

Yeah I'm fine with that, and it should be too difficult to add. Not sure when I'll have time but I'll try to implement that in the next few days.

**Comment by johannesnagl** [comment]
I had the previous version installed and a simple brew upgrade did not add
the new command. Although it says I’m having the latest git hash checked
out.

**Comment by bepaald** [comment]
>I had the previous version installed and a simple brew upgrade did not add
the new command. Although it says I’m having the latest git hash checked
out.

I believe you need to `brew upgrade --fetch-HEAD` to upgrade. Maybe you could test that for me? I'll add it to the readme if it works.

**Comment by johannesnagl** [comment]
i just did `brew remove …` & `brew install --HEAD …` and it worked!

**Comment by bepaald** [comment]
Done (the new push should add reactions to txt export). Thanks for the help!

**Comment by johannesnagl** [comment]
so, the upgrade works as you mentioned with `brew upgrade --fetch-HEAD ./homebrew/signalbackup-tools.rb`

however, executing the following command:

```
signalbackup-tools file.backup "XXX" --exporttext ./output
```

returns the following error:

```
signalbackup-tools (signalbackup-tools) source version 20230716.100017 (OpenSSL)
[ Error parsing command line option `--exporttext': Unknown option. ]
[ Error parsing command line option `./output': Unknown option. ]
[ Error parsing command line option `./output': Unknown option. ]
Error parsing arguments
Try 'signalbackup-tools --help' for available options
```

same command, with `--exporthtml` works.

**Comment by johannesnagl** [comment]
might be related to https://github.com/bepaald/signalbackup-tools/commit/9db1692699cf5df8cbfde1153602faf9349aebc7#diff-4b029ad20a163c83c8e955e1716678db95df156c941c8bd46d8eb6b80a1c25dcR101 - seems you had a c/p error and redefined `exporthtml` again instead of `exporttext`?

**Comment by johannesnagl** [comment]
ok, works like a charme, if you use the proper argument. When using `exporttxt` it works. My bad 😢

**Comment by bepaald** [comment]
>ok, works like a charme, if you use the proper argument. When using exporttxt it works. My bad cry

Haha, yes that helps. Still good catch on the typo in the help-output, I've fixed that one now.

Glad it's working, let me know if you have any more suggestions for this, otherwise feel free to close this issue (new ones can always be opened later if needed).

Thanks for the help!

**Comment by johannesnagl** [comment]
@flux77 what do you think?

**Comment by flux77** [comment]
I wasn't able to compile the code to test it. I am at commit 5e6eb4e148e483ba2bb76fe364628ead09fc339f.

Excerpt of compilation error when I run `./BUILDSCRIPT.sh`:

```
BUILDING (132/141): /usr/bin/g++-10 -c -Wall -Wextra -Wshadow -Wold-style-cast -Woverloaded-virtual -pedantic -std=c++2a -O3 -march=native -flto  -o "filedecryptor/o/getframe.o" "filedecryptor/getframe.cc"
filedecryptor/getframe.cc: In member function ‘std::unique_ptr<BackupFrame> FileDecryptor::getFrame()’:
filedecryptor/getframe.cc:77:155: error: expected primary-expression before ‘!=’ token
   77 | t(), reinterpret_cast<unsigned char *>(&encrypted_encryptedframelength), sizeof(decltype(encrypted_encryptedframelength))) != 1) != 1) [[unlikely]]
      |
```

* GCC version: gcc-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
* OS: Ubuntu 20.04.6

**Comment by bepaald** [comment]
Oops sorry, I see there is a typo in the OpenSSL 1.1 codepath. I'm running OpenSSL 3 myself, and apparently github actions does as well. I will fix this as soon as I get home (in a few hours probably).

If you wanted to test before that, you could just remove the doubled `!= 1)` from the end of the line (77 in filedecryptor/getframe.cc).

Apologies, I'll try to add a test for the automated builds so I get notified when I push stuff like this to the lesser used codepaths.

**Comment by flux77** [comment]
Thank you. I managed to compile the program.

I have tried the `--exporttxt` option. I managed to export all my chats to plain text :smile:. However, the exit code is 1. Is that normal?

This is the last part of the console output:

```
Reading backup file...
FRAME 5626 (100.0%)... Read entire backup file...

done!
Dealing with thread 2
Dealing with thread 3
Dealing with thread 4
Dealing with thread 5
Dealing with thread 6
Dealing with thread 7
Dealing with thread 8
Dealing with thread 9
Dealing with thread 10
```

**Comment by flux77** [comment]
I had a closer look at the code and Signal's database schema.

Suggestion regarding attachments:

`--exporttxt` currently shows attachments as `[2023-07-10 01:26] *** <bob> sent file of type image/jpeg` when the "file_name" is NULL in the "part" table. Would it be possible to show attachments in the form `[2023-07-10 01:26] *** <bob> sent file "signal-2023-07-10-012656.jpg"` instead?

I observe that the `signal-2023-07-10-012656.jpg` format is the same as that output by the `--dumpmedia` option, which seems to be based on the "date_sent" timestamp of the "message" table. In this way, the result of `--exporttxt` would be able to reference attachment files output by `--dumpmedia`.

**Comment by bepaald** [comment]
Ok, I fixed the typo in the openssl1 code and added a test in github to notify me if I add new bugs in the legacy code in the future.

>Thank you. I managed to compile the program.

>I have tried the --exporttxt option. I successfully exported all my chats to plain text smile. However, the exit code is 1. Is that normal?

Excellent. The exit code is indeed a bug, I tend to write a `return 1` (or `false` or whatever the bad condition is) as boilerplate code and only change that when a function is completed, which I forgot in this case. Should be fixed now. Thanks!

>Suggestion regarding attachments:

Not sure about that one. The way it's written would sort of look like an actual file with that name was sent (while it wasn't). The attachments' date can already (mostly) be cross referenced from the `[2023-07-10 01:26]` part at the beginning of the line. Though I admit, that is not optimal. I'll try to think about some other way to clearly reference the filenames used by `--dumpmedia` without implying untrue events. (And of course I'm open to other suggestions for this).
