### ISSUE TITLE
Signal 6.26.2 backup file can't be extracted, stuck in "brute forcing to next valid frame" loop

### ISSUE THREAD

**Issue by alexlance** [bepaald/signalbackup-tools#131]
Using a command like this:

```
/usr/bin/signalbackup-tools --input signal-2023-07-15-13-00-57.backup --output bits/ --password ... 
```

It gets stuck trying to do a "brute force to the next valid frame" and the CPU goes to 100% - I left it like this for over half the day and it never found the next frame. The output was:

```
signalbackup-tools (/usr/bin/signalbackup-tools) source version 20230711.150813 (OpenSSL)                                                      
IV: (hex:) ... (size: 16)                                                                          
SALT: (hex:) ... (size: 32)                        
BACKUPKEY: (hex:) ... (size: 32)                   
CIPHERKEY: (hex:) ... (size: 32)                   
MACKEY: (hex:) ... (size: 32)                      
COUNTER: 3411718425                                                                                                                            
Reading backup file...                                                                                                                         
Getting frame at filepos: 60 (COUNTER: 3411718425)                                                                                             
FRAME 0 (000.0%)...                                                                                                                            
Getting frame at filepos: 60 (COUNTER: 3411718425)                                                                                             
Framelength: 1384597236                                                                                                                        
Failed to read next frame (1384597236 bytes at filepos 60)                                                                                     
Starting brute forcing offset to next valid frame... starting after: 60                                                                         
Checking offset 784834050 bytes
```

It basically keeps ticking forward and never proceeding to extract the backup. Tried it with two separate backup files - that were newly created using the latest version (as of today) of Signal 6.26.2.

**Comment by bepaald** [comment]
Hi! Thanks for the info. I was aware of a breaking change in the backup format (https://github.com/signalapp/Signal-Android/commit/c6473ca9e63236af3eae9959a50cfa643d53272e), but thought it was still in beta.

I do have this fixed locally, but wanted to test it a little more. Give it a few hours, it should be fixed when I next push.

**Comment by bepaald** [comment]
Are you sure you're not on the beta channel?

**Comment by alexlance** [comment]
Yep - I've never opted into the beta version of Signal. However when I look at the Download APK page for Signal it offers 6.25.5 - whereas as mentioned above I'm running 6.26.2 (built from source because I wanted to keep sms/mms functionality - see https://github.com/alexlance/signal-android-classic) 

Argh. Am I running beta and don't know that I'm running beta?

**Comment by bepaald** [comment]
>Argh. Am I running beta and don't know that I'm running beta?

Yup, looks like it. Very brave of you 😃 No worries though, this will still be fixed fairly quickly.

**Comment by alexlance** [comment]
Ok - lucky me! 

I miight downgrade to 6.25.5 (i.e. restore from yesterday's backup to older version) and add a check in the future not to get ahead of their published APK version. Thanks for letting me know. :+1: 

(ps: definitely no need to hurry a patch on my account - just wanted to check if it was something I was doing wrong - and I was :)

**Comment by bepaald** [comment]
Ok, I've pushed the update, I hope it works! Maybe you could let me know. Thanks!

**Comment by alexlance** [comment]
I've just rebuilt from master and can confirm that all is good 🚀 

Many thank yous for the fix. And more generally thank you for this tool! It really helps restore a lot of power and flexibility back to the Signal end user.
