### ISSUE TITLE
Possible to Import from Android backup to MacOS Signal desktop? 

### ISSUE THREAD

**Issue by palmerj** [bepaald/signalbackup-tools#134]
Is this possible e.g by using merge backups? I want to import my message history onto the desktop version on a new MacOS install. 

Note I have a linked desktop on another macbook, but it's missing a couple months of messages (I just relinked it now) Maybe that can help?

**Comment by bepaald** [comment]
Unfortunately not. The merge functionality is really only for two android backups. The desktop database has practically no similarity to the android db, so merging them is non-trivial to put it mildly.

I've responded to this same question a while ago, in that case the user mentioned something about implementing the functionality themselves. Possibly they can help you further. Link: #116
