### ISSUE TITLE
Unsupported database version

### ISSUE THREAD

**Issue by spawnpeekboi** [bepaald/signalbackup-tools#136]
As title stated
When tried to restore backup
Terminal stated that the database version is 121
And stated the current unsupported database version (121). Please upgrade your database or append the --migratedb option to attempt to migrate database to a supporter version

-h didn't state the option for --migratedb

Log as following
```

signalbackup-tools (signal.exe) source version 20230730.120659 (OpenSSL)
IV: (hex:) XXX (size: 16)
SALT: (hex:) XXX (size: 32)
BACKUPKEY: (hex:) XXX (size: 32)
CIPHERKEY: (hex:) XXX (size: 32)
MACKEY: (hex:) XXX (size: 32)
BACKUPFILE VERSION: 0
COUNTER: XXX
Reading backup file...
FRAME XXX (100.0%)... Read entire backup file...

done!
Database version: 121
Error: Currently unsupported database version (121). Please upgrade
       your database or append the `--migratedb' option to attempt to
       migrate this database to a supported version.

```

**Comment by spawnpeekboi** [comment]
Never mind didn't check the closed issue
Sorry for the inconvenience caused

**Comment by bepaald** [comment]
No worries, I just added the `--migratedb` option to the help output. Thanks!

**Comment by spawnpeekboi** [comment]
oh thanks
i first ran
`signalbackup-tools.exe -i signal.backup --migratedb` 
though it will upgrade the db version
