### ISSUE TITLE
Bad MAC when trying to decrypt old backup from Signal 4.78.5

### ISSUE THREAD

**Issue by KeefeJ** [bepaald/signalbackup-tools#137]
Does signalbackup-tools support backups from Android Signal 4.78.5 (Nov 24, 2020), or was the format different back then?

In the Signal app on this old and not-updated phone, I did the passphrase verification process to ensure I'm using the correct passphrase for this backup which I just created from the app.

But this is what I get from the attempt to decrypt the backup file with this tool:
```signalbackup-tools_win.exe signal-2023-08-11-02-54-47.backup "***** ***** ***** ***** ***** *****" -o decrypted-signal-2023-08-11-02-54-47
signalbackup-tools (signalbackup-tools_win.exe) source version 20230813.194453 (OpenSSL)
IV: (hex:) ba ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** (size: 16)
SALT: (hex:) 67 ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** (size: 32)
BACKUPKEY: (hex:) 91 ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** (size: 32)
CIPHERKEY: (hex:) 7e ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** (size: 32)
MACKEY: (hex:) 89 ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** (size: 32)
BACKUPFILE VERSION: 0
COUNTER: 3*********
Reading backup file...
FRAME 0 (000.0%)...
WARNING : Bad MAC in frame: theirMac: (hex:) d0 ** ** ** ** ** ** ** ** **
                              ourMac: (hex:) 4a ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** **
 *** NOTE : IT IS LIKELY AN INCORRECT PASSWORD WAS PROVIDED ***
Failed to get valid frame from decoded data...
Encrypted data had failed verification (Bad MAC)
Starting bruteforcing offset to next valid frame... starting after: 58
Checking offset 169136860 bytesFailed to read 4 bytes from file to get next frame size... (-1 / 169136929)
Failed to read 4 bytes from file to get next frame size... (-1 / 169136929)
Checking offset 169136870 bytesFailed to read 4 bytes from file to get next frame size... (-1 / 169136929)

done!
WARNING EndFrame was not read: backup is probably incomplete
Database version: 4294967295

Exporting backup into 'decrypted-signal-2023-08-11-02-54-47/'
Writing HeaderFrame...
Writing DatabaseVersionFrame...
Error: asked to write nullptr frame to disk
Failed to export backup to 'decrypted-signal-2023-08-11-02-54-47'

**Comment by bepaald** [comment]
Hi! 

While yes, the format was different back then, this program supports all backup versions at this moment (though some select functions do not support very old databases (yet)). For example with a backup of around the same time as yours:
```
[~/programming/signalbackup-tools] $ ./signalbackup-tools ~/PHONE/signal-2020-11-01-13-36-15.backup [passphrase]
signalbackup-tools (./signalbackup-tools) source version 20230813.165938 (OpenSSL)
IV: (hex:) fd [...]
SALT: (hex:) 37 [...]
BACKUPKEY: (hex:) 15 [...]
CIPHERKEY: (hex:) 0e [...]
MACKEY: (hex:) b2 [...]
BACKUPFILE VERSION: 0
COUNTER: 4[...]
Reading backup file...
FRAME 61561 (100.0%)... Read entire backup file...

done!
Database version: 79
[~/programming/signalbackup-tools] $ 
```

And even much older (the oldest I have):
```
[~/programming/signalbackup-tools] $ ./signalbackup-tools ~/PHONE/DEVsignal-2018-04-26-21-47-19.backup [passphrase]
signalbackup-tools (./signalbackup-tools) source version 20230813.165938 (OpenSSL)
IV: (hex:) 09 [...]
SALT: (hex:) f6 [...]
BACKUPKEY: (hex:) 4c [...]
CIPHERKEY: (hex:) 6b [...]
MACKEY: (hex:) 52 [...]
BACKUPFILE VERSION: 0
COUNTER: 2[...]
Reading backup file...
FRAME 81 (100.0%)... Read entire backup file...

done!
Database version: 4
[~/programming/signalbackup-tools] $ 
```

I must say in this case, even with your verification, I'm almost 100% sure you have mistyped the passphrase. Could you double/triple/quadruple check? Do you still have Signal 4.78.5 installed so you could check if the passphrase works on there? Or so you can generate a new backup with a new password?

**Comment by KeefeJ** [comment]
Thanks for the fast reply, and for developing this tool!

I did check the passphrase multiple times. Is it significant that theirMac and ourMac are different lenghts?

Sadly, I foolishly upgraded Signal to 6.0.6 and then to 6.1.3 after copying the backup files off the phone, without any other low-level (e.g. Titanium) phone backup. And now Signal hangs on a white screen, so I might be SOL on trying to create another backup from the app.

**Comment by KeefeJ** [comment]
Oh wow, this looks like my bad!

I just looked on the phone again and found another Signal backup from Aug 13, and it decrypts fine in your tool! I don't know how I missed that file the first time (can I blame the buggy MTP system? lol), and thought the Aug 11 and Aug 12 backups were the ones after I had changed the passphrase in the app (because I lost the old passphrase). I thought Signal deleted old backups when the passphrase is changed.

Anyway, it seems you were correct, and the passphrase I was using was the wrong one for those older backup files.

Thanks!

**Comment by bepaald** [comment]
Ha great! I was just typing a reply to your previous message (with the only recommendation to reinstall the old Signal version, I found you can still get the apk through some mirrors online if you trust them).

But I'm glad you have it sorted! Buggy MTP is definitely a good possibility, that's known to happen.

Thanks for reporting back!
