### ISSUE TITLE
truncated Postings in HTML export.

### ISSUE THREAD

**Issue by Michael33X** [bepaald/signalbackup-tools#139]
Thank you for your dedication and the great tool.

I have a problem with the export to HTML. One of my chats contains very long posts. Partly these are short stories that we send to each other. When exporting to HTML, these texts are truncated, after about 2000 characters, spaces included. Is this a limitation of signalbackup-tools or do I have to disable this truncation with a command.

With kind regards

**Comment by bepaald** [comment]
Hi! Thanks for notifying me of this. I do remember (very) long messages being stored differently in the database, but I never considered them when creating the exporthtml function.

I'll try to test and fix this tomorrow, if it's more work than I think it might be Monday before I get around to it. But I'll definitely work on this as soon as I can.

Thanks again!

**Comment by Michael33X** [comment]
Oh, thank you very much in advance.

Here I am again with an addition.

I want to use the HTML export to put these long postings into a novel.
I noticed that when these long postings are truncated, then in the HTML export of the posting in question, there is always a reference to an attachment, a file, in the header. With shorter postings this attachment is missing.

e.g.


```
Attachment 'signal-2023-08-13-151110.txt'[🠟](file:///E:/xxxx/html/Hexe%20(_id11)/media/Attachment_230_1691932270906.bin)
-----------
Ok, I see.

Small change of subject
Then I need a break.

**********************
Another text like that,   ....
```

I hope this helps you find the cause and you can fix this.
Thanks again

**Comment by Michael33X** [comment]
Further addition:

This attachment file, see 'Attachment_230_1691932270906.bin' above, contains the entire text of the posting. I just looked it up. For me, it would now be desirable if the entire text (without reference to an attachment) was in the HTML export.
Perhaps such an expand function, could also be a command line option.

Thanks a lot

**Comment by bepaald** [comment]
Yes that's right, for long messages, where the Android app also truncates the message and says '*Read more...*', the message body is actually an attachment to the message, just like a picture would be. I knew this, but just forgot about it when implementing, but I think I've just fixed it.

>For me, it would now be desirable if the entire text (without reference to an attachment) was in the HTML export.

This is exactly what I did. Let me know if it works correctly with the current version or if you're still seeing any errors.

Thanks again!

**Comment by Michael33X** [comment]
Many, many thanks,

You work at the speed of light. I would not have expected that. I need a little more time to try the change. I see that you have already compiled a new Windows version.
Wow, thank you very much for your commitment.

I'll be in touch soon.
Stay tuned.

**Comment by Michael33X** [comment]
I'm already back, faster than expected.
My home, weekend work had to rest briefly, because I could not wait to try your change.

Wow, it works, perfect.

Thank you so much. This helps me a lot.
Jeff

**Comment by bepaald** [comment]
Excellent, thank you for the quick response!

**Comment by Michael33X** [comment]
Hi bepaald,

I've been wanting to do this for days. I'm doing it now. I am sending you $30 as a donation to Selwin van Dijk as indicated.

Take care of yourself and stay healthy.
Jeff

[Paypal Link](https://www.paypal.com/donate/?cmd=_donations&business=U523FZFW3BQBQ&currency_code=USD&source=url)

**Comment by bepaald** [comment]
Hi Jeff, thank you so much for your generous donation! It is greatly appreciated.

I hope this program will remain useful to you in the future. Thanks again!
