### ISSUE TITLE
contact_name="null"

### ISSUE THREAD

**Issue by foegra** [bepaald/signalbackup-tools#14]
I haven't seen any user having the same problem, but me - when exporting xml or csv = the contacts area is empty. 
In case of xml file - it says contact_name="null"
Tried both Signal app versions:
Stable 4.72.5
Beta 4.72.6
When i restore the backup file inside the app itself - everything works as it should

I was using latest Windows precompiled app (20200913)

**Comment by foegra** [comment]
Hello!
Thank You for Your respond. 
I did as You said:
In my case - it uses only phone row as a recipient
Other fields are empty. 

My goal is to get those messages back to Native Android SMS app With SMS Backup&Restore.
According to that program - it uses "address" field in it's xml file for a recipient. However, in the imported Signal backup "address" field is empty. 
If there was a way to put phone number in the address field, I am pretty sure - it would fix the issue.

**Comment by bepaald** [comment]
I'm not sure I completely understand the problem. Are there no names at all in the database? Does the signal app show any names, or are the threads in the app also only identified by phone numbers?

As for the 'address' field in the XML, that is indeed supposed to be the phone number, for example, one specific line from the XML I exported yesterday from a 4.72.5 backup (I just censored the phone number manually):
```
 $ grep 1599811311114 current.xml 
<sms protocol="0" address="+316XXXXXXXX" contact_name="Devphone Black" date="1599811311114" readable_date="Sep 11, 2020 10:01:51" type="2" subject="null" body="Test" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
```
In your XML file the address field is just `address=""`? Are the other fields (especially 'body') correctly filled in? If you run `signalbackup-tools backupfile.backup passwd --runprettysqlquery "SELECT DISTINCT phone FROM recipient"`, do you see all the phone numbers?

I have also just pushed a new version which prints some error messages when it fails to retrieve the phone numbers during XML output, so I expect the same problem, but maybe you can run it again and copy paste the output you get when running the program.

**Comment by foegra** [comment]
Here is the error of updated application:
`ERROR Failed to retrieve required field 'address' (sms (1))`

Here how looks my exported SMS into xml file:
`<sms protocol="0" address="" contact_name="null" date="1596906763346" readable_date="Aug 08, 2020 " type="2" subject="null" body="Mārtiņ, sveiks!" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />`

Here is the response for `--runprettysqlquery "SELECT DISTINCT phone FROM recipient"` command:

`* Executing query: 29554***
SQL error during sqlite3_prepare_v2(): near "29554***": syntax error` 

Backup is not corrupted and restores in Signal just Right!

> I exported yesterday from a 4.72.5 backup

Did You do this on Windows?

**Comment by bepaald** [comment]
Thanks! I think I found the problem. When retrieving the address, my program checks for a valid sql query result by checking wether the returned address is a TEXT-type, as that is what the type of the column used to be. However, these days, the address is a INTEGER-type column. I never noticed that, because in SQLite columns can't be changed, so in my backups the column is still TEXT, and only in newly created databases (somewhat recent fresh installations) is it an INTEGER.

Please give me a little while to fix it.

**Comment by bepaald** [comment]
Would you please try again? Any errors or other information you think would be interesting for me would be appreciated. Thanks!

**Comment by bepaald** [comment]
Ok, how about now... Would you please try again? Any errors or other information you think would be interesting for me would be appreciated. Thanks!

**Comment by foegra** [comment]
This is fantastic!
I've almost lost any hope of getting my messages back. 
Now - everything works just fine!
I wish You success in any further activities!
