### ISSUE TITLE
Failed to open back up

### ISSUE THREAD

**Issue by Stargazer76434** [bepaald/signalbackup-tools#148]
Hi there,

I am trying to run the file on windows, but receiving the following:

![Screenshot_20230923_164525_Video Player](https://github.com/bepaald/signalbackup-tools/assets/145856105/e6ab5a31-c8dc-4d4f-b86f-80794161ed5f)

Any idea what could be wrong?

Thanks

**Comment by bepaald** [comment]
Hi! This is not a GUI application, you need to run it in a terminal. I believe on Windows people usually have 'cmd' or 'Powershell', one (or both?) of those is certainly installed by default.

Then you navigate to the directory where the tool is located and run `signalbackup-tools.exe [inputfile] [passphrase]` followed by whatever options you want the tool to do (for all the options see the README).

Let me know if this is clear, or if you need more help. Thanks!

**Comment by bepaald** [comment]
You may not need it, but I've made a little video of running this program on Windows 10. I'm going to post it here so I can link to it when other people inquire about this (you weren't the first, and you won't be the last 😃)

https://github.com/bepaald/signalbackup-tools/assets/38437099/cf6bb656-8985-4028-a12c-a8b25f1cb551

**Comment by Stargazer76434** [comment]
This helps. Thanks!

**Comment by bepaald** [comment]
👍 No worries, if you need more help, let me know.

**Comment by mnimocks** [comment]
Where does one find the Pass Phrase to use? I have a PIN on Signal, but it is not 30 characters long. Thanks.
