### ISSUE TITLE
Why doesn't the Signal foundation provide such a tool themselves?

### ISSUE THREAD

**Issue by sebastian-gerdes** [bepaald/signalbackup-tools#152]
Dear bepaald,

first of all thanks a lot for this great tool!

I think it's really great that you provide this tool for the community. I am just wondering why the official Signal developers don't provide such a tool themselves? Have you ever been in contact with them to discuss this?

Just wondering...

Best greetings,
Sebastian

**Comment by bepaald** [comment]
Hi Sebastian,

Thanks for your kind words. From you asking this question I understand you value this project, which is appreciated. However, questions like these

>Why doesn't the Signal foundation provide such a tool themselves?
>I am just wondering why the official Signal developers don't provide such a tool themselves?

Are obviously not questions for me, but for the Signal foundation, so you should ask over there. (Though I can guess the answer: limited resources and time constraints).

I have never been in contact with them to discuss anything (I wouldn't really know what to discuss either). Though, through interactions on github, I know at least some of the developers are aware of this tool's existence.

I imagine giving a tool like this any sort of endorsement or 'official status' from an organization such as Signal would require enormous quality control standards which would be completely unfeasible without some full time developers on it (right now, the quality control on this project is non-existent).

Not sure what else to comment on this, if you really want more answers you should probably take it to Signal's community forums and hope someone responds.

Thanks!
