### ISSUE TITLE
Question: how to get a backup file with newer app versions?

### ISSUE THREAD

**Issue by Klimmbimmel** [bepaald/signalbackup-tools#154]
The readme tells me to carefully check the database version and keep the version of 2 backups for merging the same. Newer versions of the app do block parts of the menu, if the app is not registered anymore. Do I need to register Signal on each old phone, make a backup and then merge them, if they have the same database version?

Additional question 2: do you have any suggestions on the order of merging more than 2 backups?

**Comment by bepaald** [comment]
>The readme tells me to carefully check the database version and keep the version of 2 backups for merging the same. Newer versions of the app do block parts of the menu, if the app is not registered anymore. Do I need to register Signal on each old phone, make a backup and then merge them, if they have the same database version?

The database version and the software version are two different things. The database version is not normally visible in the Signal app itself. This program will output it as one of the first things when run with any arguments (or even no arguments at all):
```
$ ./signalbackup-tools ~/PHONE/DEVsignal-2023-10-14-14-43-44.backup 000000000000000000000000000000
signalbackup-tools (./signalbackup-tools) source version 20231105.120039
BACKUPFILE VERSION: 1
BACKUPFILE SIZE: 69398179
COUNTER: 2422161568
Reading backup file...
FRAME 1824 (100.0%)... Read entire backup file...

done!
Database version: 209
$ 
```

(it's the last line: 209) If you need to get one of your backups more up to date, then the only option is to install Signal, restore the backup, register and export a new backup. Though unless your unlucky or the version are far apart, most versions should be fine together.

>Additional question 2: do you have any suggestions on the order of merging more than 2 backups?

Not sure, it _shouldn't_ really matter, but — I must admit — in the past it has. I guess I would try to use the 'most complete' backup as the base into which to import the other backups. 'Most complete' would be the one with the most existing conversations/contacts in it, I think. If there are large gaps in the database version it might be wise to use the newest as the base.

I hope it works for you, let me know how it goes!

**Comment by bepaald** [comment]
> Sorry, i was not very clear. I have 3 phones with the app installed and all the chats i want to merge. To get a current backup with a compatible database, i thought
> 
>     * i register one old phones / apps again, make a current backup,
> 
>     * register again the 2nd old phone and
> 
>     * finally register the new phone (with already existing chats), where I import the merged backups

Ok, sorry I misunderstood. This sounds good. So just make sure you get three backups from your three phones (for this you need to register). If the Signal version on the phones is up-to-date, the backups will all have the same (current) database version. Then you can merge them and restore the merged version back on your newest phone.

I hope that makes sense. Thanks!
