### ISSUE TITLE
Threw a 7.5GB backup at it. What happened next might surprise you!

### ISSUE THREAD

**Issue by ccoenen** [bepaald/signalbackup-tools#159]
I turned a 7.5 GB backup, spanning almost 8 years (Early 2016!) of messages in 175 conversations into an HTML export. This tool _absolutely_ rocks! I haven't found a single issue so far.

![parsing 260000 frames](https://github.com/bepaald/signalbackup-tools/assets/124909/4f0456be-c9f5-4cd7-bc79-c4748c94c6af)

Just came here to say "Thanks" 💕

(feel free to close this issue at your leisure)

**Comment by bepaald** [comment]
Ha! Thanks for your report!

I'll admit I was worried when I read the subject line, but I'm glad to read the rest of it. I've had a lousy day, so it's nice to hear some good news.

Happy it's all working, I hope it stays that way for a long while. Let me know if you ever have issues.

Thanks again!
