### ISSUE TITLE
Merge Attempt Results

### ISSUE THREAD

**Issue by mfrvnken** [bepaald/signalbackup-tools#16]
Hi, I used your tool (thank you!) to merge two Signal databases together. One was an old backup from Aug 2019 and had a database version of 11 and the other I made yesterday on database version 80. I wiped my Signal data and restored the old database into Signal to update it since you said that version difference would not merge well.

I initially tried to use my older/smaller database as the `first_database` and my newer/larger database as the `source_database`. This merge would not import into Signal and it took longer due to the iterative nature of the script since it went through the whole larger database for each thread in the database. When that failed I flipped it so the newer database was my `first_database` and my older database was my `source_database`. It took about half the time and the Signal app was able to import it.

I am not sure why the first merge would not import. I realized I didn't have a `.backup` extension on it and maybe Signal didn't like that. It didn't give me any errors or indication that it wasn't going to import the merged database it simply went to a new blank conversation window. I tried it a few times.

Thanks again! I appreciate it. You have any places to receive donations?

```
Exporting backup to 'signal-merged-2020-11-07-10-01.backup'
Writing HeaderFrame...
Writing DatabaseVersionFrame...
Writing SqlStatementFrame(s)...
  Dealing with table 'sms'... 55612/55612 entries...done
  Dealing with table 'mms'... 12434/12434 entries...done
  Dealing with table 'part'... 63/3350 entries...Warning: attachment data not found (rowid: 63, uniqueid: 1535921771541)
  Dealing with table 'part'... 590/3350 entries...Warning: attachment data not found (rowid: 594, uniqueid: 1552673824961)
  Dealing with table 'part'... 873/3350 entries...Warning: attachment data not found (rowid: 877, uniqueid: 1560209088426)
  Dealing with table 'part'... 877/3350 entries...Warning: attachment data not found (rowid: 881, uniqueid: 1560216250670)
  Dealing with table 'part'... 2184/3350 entries...Warning: attachment data not found (rowid: 2193, uniqueid: 1598130700405)
  Dealing with table 'part'... 2636/3350 entries...Warning: attachment data not found (rowid: 2649, uniqueid: 1604445062856)
  Dealing with table 'part'... 2929/3350 entries...Warning: attachment data not found (rowid: 2942, uniqueid: 1527010679847)
  Dealing with table 'part'... 3028/3350 entries...Warning: attachment data not found (rowid: 3041, uniqueid: 1531845121343)
  Dealing with table 'part'... 3039/3350 entries...Warning: attachment data not found (rowid: 3052, uniqueid: 1532717777308)
  Dealing with table 'part'... 3062/3350 entries...Warning: attachment data not found (rowid: 3075, uniqueid: 1533340237078)
  Dealing with table 'part'... 3350/3350 entries...done
  Dealing with table 'thread'... 116/116 entries...done
  Dealing with table 'identities'... 9/9 entries...done
  Dealing with table 'drafts'... 5/5 entries...done
  Dealing with table 'push'... 2/2 entries...done
  Dealing with table 'groups'... 36/36 entries...done
  Dealing with table 'group_receipts'... 4452/4452 entries...done
  Dealing with table 'job_spec'... 0/0 entries...
  Dealing with table 'constraint_spec'... 0/0 entries...
  Dealing with table 'dependency_spec'... 0/0 entries...
  Dealing with table 'sticker'... 53/53 entries...done
  Dealing with table 'recipient'... 370/370 entries...done
  Dealing with table 'storage_key'... 0/0 entries...
  Dealing with table 'key_value'... 0/0 entries...
  Dealing with table 'megaphone'... 7/7 entries...done
  Dealing with table 'remapped_recipients'... 0/0 entries...
  Dealing with table 'remapped_threads'... 0/0 entries...
  Dealing with table 'mention'... 0/0 entries...
Writing SharedPrefFrame(s)...
Writing Avatars...
Writing EndFrame...
Done!
```

**Comment by bepaald** [comment]
> Hi, I used your tool (thank you!) to merge two Signal databases together. One was an old backup from Aug 2019 and had a database version of 11 and the other I made yesterday on database version 80. I wiped my Signal data and restored the old database into Signal to update it since you said that version difference would not merge well.
> 

That's a smart move, version 11 is quite old and many things have changed in the database since then. It might have worked fine, but I can certainly imagine merging such an old database would have presented problems. 

> I initially tried to use my older/smaller database as the `first_database` and my newer/larger database as the `source_database`. This merge would not import into Signal and it took longer due to the iterative nature of the script since it went through the whole larger database for each thread in the database. When that failed I flipped it so the newer database was my `first_database` and my older database was my `source_database`. It took about half the time and the Signal app was able to import it.
> 

Yes, since you went through the trouble of updating the older backup, this was the way to go, purely for speed. I might actually make a note of this in the readme since it can make quite a big difference. 

> I am not sure why the first merge would not import. I realized I didn't have a `.backup` extension on it and maybe Signal didn't like that. It didn't give me any errors or indication that it wasn't going to import the merged database it simply went to a new blank conversation window. I tried it a few times.
> 

I think the missing extension was probably the problem. If I'm not mistaken the file needs that extension and have a format of numbers and hyphen that can be interpreted as a date. Otherwise the app will just not realize that a backup exists that can be imported and start with an empty conversion list. I think the fact that you didn't get any errors supports this theory. 

> Thanks again! I appreciate it. You have any places to receive donations?

Thank you very much for letting me know. I am very happy to have been able to help! I've gotten a few reports of succes by now, so I think I can update the readme to show a little more confidence. At the very bottom of the readme file are a bitcoin address as well as a Paypal link. Any donation is of course greatly appreciated but please do not feel obligated. Thanks again!
