### ISSUE TITLE
Failed to read next frame (1613426785 bytes at filepos 60)

### ISSUE THREAD

**Issue by grst** [bepaald/signalbackup-tools#167]
I am trying to extract media from a signal backup using

```
signalbackup-tools ./signal-2023-12-11-02-10-00.backup --stoponerror --dumpmedia allmedia  
```

and it fails with the following error:

```
signalbackup-tools (signalbackup-tools) source version 20220918.125919 (OpenSSL)
Please provide passphrase for input file '/home/sturm/OneDrive/signal-backup/signal-2023-12-11-02-10-00.backup': ***** ***** ***** ***** ***** *****
IV: (hex:) <redacted> (size: 16)
SALT: (hex:) <redacted> (size: 32)
BACKUPKEY: (hex:) <redacted> (size: 32)
CIPHERKEY: (hex:) <redacted> (size: 32)
MACKEY: (hex:) <redacted> (size: 32)
COUNTER: 4096992158
Reading backup file...
FRAME 0 (000.0%)... Failed to read next frame (1270912069 bytes at filepos 60)

done!
WARNING EndFrame was not read: backup is probably incomplete
Dumping media to dir 'allmedia'
Database too badly damaged or too old, dumping media is not (yet) supported, consider a full decrypt by just passing a directory as output
```

(If I omit `--stoponerror` it performs a search for the 'next valid frame' which takes forever and eventually terminates with no result)

What could cause this error? I first suspected a corrupted file, but I manually created another backup from within the signal app -- signal claims it was successful -- and then transferred it to my laptop.

So either signal (v6.40.5) writes a corrupted file while telling me the backup was successful, or `signalbackup-tools` can't deal with that file for whatever reason?

**Comment by bepaald** [comment]
Hi!

You seem to be running an ancient version of this tool (`source version 20220918.125919`). Well, ancient is a bit of an overstatement maybe, but the backup format changes regularly and it is absolutely expected that the year-old version is not capable of decrypting current backups.

So, first thing to do: get the latest version. Then please let me know if everything is alright!

Thanks!

**Comment by grst** [comment]
Ah, sorry, my bad! I am using Arch linux and installed signalbackup-tools from AUR and had naively assumed that that it gets updated automatically. Seems my AUR helper doesn't update `*-git` packages unless explicitly told to. 

The latest version works flawlessly -- Thanks for your help!

**Comment by bepaald** [comment]
No worries, thanks for reporting back. Glad it's all working!
