### ISSUE TITLE
If threadname includes "Umlaute" (äöüß)  exporting to html with "--split [N]"  there is an issue with generating link to sub pages 

### ISSUE THREAD

**Issue by hugogithubs** [bepaald/signalbackup-tools#170]
Good evening,

Version: signalbackup-tools (signalbackup-tools) source version 20231229.154347 (Win)

There is a problem in links in html export if thread names have "Umlaute" (äöüß)

For example: A thread with Name "Jörg Familiyname"
Mainpage of a thread (this works):

Link in browser: 
"file:///C:/signalbackup/test/signal-threads/J__rg%20FamilyName%20(_id35)/J__rg%20FamilyName.html"

Filename in file system: 
"J__rg FamilyName.html"

html source:
"<a href="J__rg%20FamilyName%20(_id35)/J__rg%20FamilyName.html" class="main-link"></a>"

Failure if navigating to next page / page 1:
Link in browser:
"file:///C:/signalbackup/test/signal-threads/J__rg%20FamilyName%20(_id35)/J%c3%b6rg%20FamilyName_1.html"
Filename in file system:
"J__rg FamilyName_1.html"

html source:
"<a href="J%c3%b6rg%20FamilyName_1.html">"

**Comment by hugogithubs** [comment]
Oh, html code was automatically removed from post...

**Comment by bepaald** [comment]
Thanks for reporting! I'm not at home at the moment, and have a busy day today so I probably won't have time. I think I see the problem though, hopefully I'll have this fixed tomorrow. I'll update here once I do. Thanks again!

**Comment by bepaald** [comment]
I gave this a go _very_ quickly. Let me know if it works now. I won't have time today anymore, if it's still giving problems I'll look at it again tomorrow. Thanks!

**Comment by hugogithubs** [comment]
Hi,
thank you for this quick release. 
I just tested your last release regarding this issue  and it works fine now! 

Thank you very much and I wish you a happy new year

**Comment by bepaald** [comment]
Thanks for reporting back, glad it's working! Happy new year to you as well!
