### ISSUE TITLE
build issues on Debian 11

### ISSUE THREAD

**Issue by sdettmer** [bepaald/signalbackup-tools#176]
I'm so glad I found a tool which can (I hope) test Signal backups, thanks so much!
I tried to build on Debian 11, but it comes with cmake 3,.18, but says it needs 3.19. I don't think so, at least it builds fine on Debian 11 with cmake 3.18.

**Comment by sdettmer** [comment]
Maybe https://github.com/nlohmann/cmake_min_version helps:
steffen@lia:~/tmp/cmake/cmake_min_version (master u=) $ venv/bin/python cmake_min_version.py ~/work/signal-backup-tool/signalbackup-tools -- -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -B b
Found 56 CMake binaries from directory tools

```
[  0%] CMake 3.14.7 ✔ works
[ 14%] CMake 3.7.2  ✘ error
       The source directory "/tmp/tmp1p81esd9/b" does not exist.
[ 29%] CMake 3.11.0 ✘ error
       The source directory "/tmp/tmpmb7sq65z/b" does not exist.
[ 43%] CMake 3.12.4 ✘ error
       The source directory "/tmp/tmp9h7pgnu0/b" does not exist.
[ 57%] CMake 3.13.5 ✘ error
       CMakeLists.txt:16 (find_package)
[ 83%] CMake 3.14.0 ✔ works
[100%] Minimal working version: CMake 3.14.0

cmake_minimum_required(VERSION 3.14.0)
```

**Comment by sdettmer** [comment]
mmm no pull requests? But what instead?
I added some github test action, set minimal version to 3.14 and tested it on my local Debian 11 and githubs ubuntu-latest, see here:

https://github.com/bepaald/signalbackup-tools/compare/master...sdettmer:signalbackup-tools:dev/sde/cmake-min-ver

```
commit cb87b802a98f605b3a34ac3fbee371e6f4c86eab (HEAD -> dev/sde/cmake-min-ver, sde/dev/sde/cmake-min-ver)
Author: Steffen Dettmer <steffen.dettmer@gmail.com>
Date:   Wed Jan 10 01:33:06 2024 +0100

    set cmake_minimum_required to 3.14

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 63b34da..46df0fd 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,4 +1,4 @@
-cmake_minimum_required(VERSION 3.19)
+cmake_minimum_required(VERSION 3.14)

 set(CMAKE_CXX_STANDARD 20)
 set(CMAKE_CXX_STANDARD_REQUIRED on)
````

**Comment by bepaald** [comment]
Thank you for reporting. At the time of creating, the minimum version was simply set to whatever current version was instilled. I never bothered to check older versions.

>mmm no pull requests? But what instead?

This! You are doing it right. Should be fixed. Thanks again!
