### ISSUE TITLE
.exe will not launch or install

### ISSUE THREAD

**Issue by Dr1ftwood** [bepaald/signalbackup-tools#18]
Briefly a "skype" icon pops up on the task manager, goes away after a few seconds after clicking the .exe

Program doesn't appear to launch.

Using latest version of windows 10.

**Comment by bepaald** [comment]
I'm not sure what you are trying to do, but please note that this is a console application, with no GUI. You can not just double click the icon, you must run this from a command line (cmd.exe by default in Windows I believe).

I have no idea why a skype icon would pop up, must a weird Windows thing.

Let me know if you have other questions.
