### ISSUE TITLE
export Signal settings and lost of blocked contacts & groups

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#189]
Nothing important but we could also add an option to render a html overview of all blocked contacts and might as well throw in Signal Android settings. --includeBlockedList --includeSettings

**Comment by bepaald** [comment]
Blocked contacts should be easy. I'll see about the settings, I think _something_ can be done.

**Comment by bepaald** [comment]
I started on the blocked contacts, you could test that one out and give notes if any (`--includeblockedlist`). 

For the settings nothing (at least not much) is implemented yet, but here is a work in progress:

![settingspage](https://github.com/bepaald/signalbackup-tools/assets/38437099/86a7c54a-5853-471e-9170-507c6232cc3d)

(I noticed I had some text selected during the screenshot, that is not actually blue :) )

I plan to keep it simple by using the raw key names, and not not actually trying to maintain a list of keys translate them into natural language. Again, any notes welcome.

**Comment by bepaald** [comment]
Btw, there are generally quite a few more 'SharedPreferences' (you can see them when exporting a backup to directory, just open the files with any plain text viewer).

I only plan to include the ones starting with _'settings'_. None of the other ones seem to be settings the user has any control over, and most people will not know what they mean anyway. There are even some (public _and private_) keys in there that I would not want to accidentally export.

**Comment by bepaald** [comment]
Any comments on `--includesettings`?

**Comment by Meteor0id** [comment]
Looking great!

**Comment by bepaald** [comment]
> Looking great!

That's good to hear. I've added this to the README and help-output. Thanks!
