### ISSUE TITLE
Missing index in HTML report 

### ISSUE THREAD

**Issue by denyzkoo** [bepaald/signalbackup-tools#192]
Hi 

in new version i miss index.html (Signal conversation list).

**Comment by bepaald** [comment]
I can not reproduce this. could you please show the exact command you are using (leave out the passphrase) and the full output of the program?

Thanks!

**Comment by denyzkoo** [comment]
comand is: 

signalbackup-tools_win.exe signal-2024-02-29-13-47-17.backup 8****************************************7 --exporthtml Report --includecalllog --themeswitching

Inside Report folder are only uses chats. no index.html file

**Comment by bepaald** [comment]
Thank you for reporting back. This is very strange. I assume there is also no `calllog.html` in the Report folder?

Could you show me the output of the command? When I do it on a Windows machine, I get:
```
C:\Users\User\Desktop\SIGNALBACKUP-TOOLS>signalbackup-tools_win.exe DEV2signal-2024-02-15-15-54-17.backup 7****************************7 --exporthtml Report --includecalllog --themeswitching
 *** Starting log:   ***
signalbackup-tools (signalbackup-tools_win.exe) source version 20240228.165934 (Win)
BACKUPFILE VERSION: 1
BACKUPFILE SIZE: 127467570
COUNTER: 3820351285
Reading backup file...
FRAME 1294 (100.0%)...
Read entire backup file...
done!
Database version: 219
Dealing with thread 2
Dealing with thread 3
Dealing with thread 5
Dealing with thread 6
Dealing with thread 7
Writing index.html...
Writing calllog.html...
All done!
```

Note the `Writing index.html` (and `calllog.html`) in there. After it's done, the Report folder contains:
```
C:\Users\User\Desktop\SIGNALBACKUP-TOOLS>dir Report\index.html
 Volume in drive C has no label.
 Volume Serial Number is C6A9-58C7

 Directory of C:\Users\User\Desktop\SIGNALBACKUP-TOOLS\Report

01-03-2024  09:24            15.459 index.html
               1 File(s)         15.459 bytes
               0 Dir(s)  23.576.518.656 bytes free
```

Could you show me your output? Maybe some error is printed. If you look at the chats that are exported, do you think they are complete, or are some missing?

Thanks!

**Comment by bepaald** [comment]
Thanks again. It looks indeed like there is something going wrong here. I'm afraid debugging is always pretty difficult as I do not have access to your backup file. So I hope you understand I will have to ask you to help me if you can. I hope that's OK.

It is currently my guess that there is some specific message in thread 87 that is causing the program to crash. Could you please test the same command again, first by adding `--limittothreads 87`, and then again with `--limittothreads 85` and let me know the results. My guess is that in the first case, the results are the same (no 'index.html'), but in the second the program succeeds.

Thank you!

**Comment by denyzkoo** [comment]
T:\JAN\New>signalbackup-tools_win.exe signal-2024-02-29-13-47-17.backup 865861948462076533711860831347 --exporthtml Report87 --includecalllog --themeswitching --limittothreads 87
 *** Starting log:   ***
signalbackup-tools (signalbackup-tools_win.exe) source version 20240228.165934 (Win)
BACKUPFILE VERSION: 1
BACKUPFILE SIZE: 136167289
COUNTER: 3729850364
Reading backup file...
FRAME 19045 (100.0%)...
Read entire backup file...
done!
Database version: 215
Dealing with thread 87

T:\JAN\New>signalbackup-tools_win.exe signal-2024-02-29-13-47-17.backup 865861948462076533711860831347 --exporthtml Report85 --includecalllog --themeswitching --limittothreads 85
 *** Starting log:   ***
signalbackup-tools (signalbackup-tools_win.exe) source version 20240228.165934 (Win)
BACKUPFILE VERSION: 1
BACKUPFILE SIZE: 136167289
COUNTER: 3729850364
Reading backup file...
FRAME 19045 (100.0%)...
Read entire backup file...
done!
Database version: 215
Dealing with thread 85
Writing index.html...
Writing calllog.html...
All done!

report 85 - have index and callog as well. 
report 87 - blank html,  0 B

**Comment by bepaald** [comment]
Thanks again. I have created a special version of the program which shows some more output. Here: [signalbackup-tools_win.zip](https://github.com/bepaald/signalbackup-tools/files/14461613/signalbackup-tools_win.zip). This will not fix the problem, it is only to help me find where the problem is.

Could you please use this version and run again, with `--limittothreads 87`? I would be interested in the output starting with `Dealing with thread 87`. Thank you so much for your help!

**Comment by bepaald** [comment]
Thanks again, we're getting close. One more time please, with this new version: [signalbackup-tools_win.zip](https://github.com/bepaald/signalbackup-tools/files/14461964/signalbackup-tools_win.zip).

I'm expecting a new last line `[DEBUG] :   GROUP INFO: .......`. I hope with that line I can find the problem and fix it.

**Comment by denyzkoo** [comment]
T:\JAN\New>signalbackup-tools_win-t.exe signal-2024-02-29-13-47-17.backup 865861948462076533711860831347 --exporthtml Report87test --includecalllog --themeswitching --limittothreads 87
 *** Starting log:   ***
signalbackup-tools (signalbackup-tools_win-t.exe) source version 20240228.165934 (Win)
BACKUPFILE VERSION: 1
BACKUPFILE SIZE: 136167289
COUNTER: 3729850364
Reading backup file...
FRAME 19045 (100.0%)...
Read entire backup file...
done!
Database version: 215
Dealing with thread 87
[DEBUG] : thread_id: 87 isgroup: 1
[DEBUG] : Got 3 messages to import (thread 87)
[DEBUG] : Creating directory: 'Report87test/Blava (_id87)'
[DEBUG] : Split: -1 msgs: 3 msg/page: 3 npages: 1
[DEBUG] : Opening output: 'Report87test/Blava (_id87)/Blava.html'
[DEBUG] : HTMLwriteStart()
[DEBUG] :   isgroup 1
[DEBUG] :   isgroup 2
[DEBUG] :   getGroupInfo()
[DEBUG] :   GROUP INFO: EgVCbGF2YSIAKgYIAhACGAMwAkJwChDyYfwXUuhKe4DEcK6b720KEAEaEOKnkLBVd0rzpcMbSyG0h1wgleiCp8wxKkEAWGTG/h+8+BqJtGFEhQj8CxKKNRziycF1osDQSpTuaiBsrK0Rs/SRtbzEF3QiFoNHwpoIz8kT8TDJduhhhGN2KFIQDtuNeoUJOLhyqlBGtokK4WAC

**Comment by bepaald** [comment]
Thank you so much. I think I fixed it (it was a stupid copy-paste mistake I made). Please update (from the [releases page](https://github.com/bepaald/signalbackup-tools/releases/tag/20240301)) and try again. Let me know if it works now.

**Comment by denyzkoo** [comment]
It worked very well. Thank you for fast support.
