### ISSUE TITLE
README.md changes for Debian

### ISSUE THREAD

**Issue by taggart** [bepaald/signalbackup-tools#20]
On Debian to build I had to 

`apt install libsqlite3-dev libssl-dev g++`

and to invoke BUILDSCRIPT.sh I had to use bash because Debian's /bin/sh is provided by dash and the script has some bashisms in it. Debian Buster is g++ 8 and clang 7, bullseye (still in dev) g++ 10 and clang 9.

**Comment by bepaald** [comment]
I think I should rewrite that section of the README sometime soon. All the talk about the Fedora live image was just there for Windows users unfamiliar with Linux and compiling software. But now, a working Windows is provided so I should probably not mention any specific Linux distro. I certainly can't provide a comprehensive list of all the different naming conventions different distros use for development packages. I'll write something new when I have some spare time.

The script should be fixed to work with dash now.

Thanks!
