### ISSUE TITLE
Option to export all media files from a chat

### ISSUE THREAD

**Issue by Outlet2048** [bepaald/signalbackup-tools#201]
While reading through the readme I didnt find an option that allows me to export all media files from a specific chat
This would be really useful as I have a chat with 12k media files and Signal fails to export it using inbuilt options.

Is there a way to do this / a potential for this to be a FR?

Cheers

**Comment by bepaald** [comment]
Hi! Thanks for your report.

>While reading through the readme I didnt find an option that allows me to export all media files from a specific chat

I think you may be missing something in the README (or the README is not clear?). See: https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#dumpmedia

Summarized: the `--dumpmedia [dir]` option should export all media to the directory `dir`. The options `--limittothreads [N]` (obtain `N` from `--listthreads`) or `--limittothreadsbyname "Bob"` can be added to limit the chats from which media is exported.

Please let me know if this works correctly or if you need more guidance.

Thanks!

**Comment by bepaald** [comment]
No worries! Thanks for the suggestion, I just added the `--excludestickers` option to use with `--dumpmedia`. I only tested it briefly, but I think it should work.

Thanks!
