### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by neitsab** [bepaald/signalbackup-tools#22]
Hi, thanks for your software, I just used it to successfully merge an old backup with my current one (I sent you an email  with feedback about it).

As I'm on Arch and noticed it wasn't yet packaged in the AUR, I went on and created one: [signalbackup-tools-git](https://aur.archlinux.org/packages/signalbackup-tools-git/).

As such I thought I'd do my due diligence and report the one warning I got from namcap:

    signalbackup-tools-git W: Unused shared library '/usr/lib/libm.so.6' by file ('usr/bin/signalbackup-tools')

A cursory search revealed that people in that situation [tended ](https://github.com/maxmind/libmaxminddb/issues/114)to [report](https://github.com/jackaudio/jack2/issues/430) it upstream, so... Here I am :grinning:

So that's it, just to let you know. Thank you very much for your work and all the best!

**Comment by bepaald** [comment]
Thanks! Should be fixed now!
