### ISSUE TITLE
can we have cropthreadsbyname accept phone numbers?

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#220]
cause note to self has my own profile name as its name, but an easier non-changing handle would be my own phone number.

**Comment by bepaald** [comment]
Done. All the `--...byname` options should now try phone number if name fails, and username if phone number also fails.

Let me know if it works as expected.

**Comment by Meteor0id** [comment]
I only tested my own phone number and it worked as expected. Thanks again!
