### ISSUE TITLE
Can it back up an active Signal Desktop installation on Windows?

### ISSUE THREAD

**Issue by 0xeb** [bepaald/signalbackup-tools#236]
@bepaald can you help me please?

I can't figure out how to export the media, messages, etc. into HTML and decrypted media from an active Signal Desktop installation on Windows.

The tool manages to decrypt the database and so on. 

But I don't know what [input] it needs so it works on the Signal appdata folder in Windows.

Please advise.

**Comment by bepaald** [comment]
Hi @0xeb!

To export the Signal Desktop database to HTML, you do not need an `[input]` file (as mentioned in [the readme](https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#desktop_functions)). Simply run:
```
signalbackup-tools_win.exe --exportdesktophtml [output_directory]
```

You could of course also add more options (see [here](https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#export-to-html) for available ones).

Let me know if that works and answers your question.

Thanks!

**Comment by 0xeb** [comment]
Thank you @bepaald , I appreciate your quick response. It works like a charm!
