### ISSUE TITLE
Workaround for no active backups on android

### ISSUE THREAD

**Issue by DeathDragonAW** [bepaald/signalbackup-tools#246]
This could be mentioned in the readme for cases where Signal is constantly crashing while backups have not been activated beforehand or passkeys have been lost.
https://transistor-man.com/restoring_android_signal_from_desktop.html
I did not test that, just stumbled upon it. 

BTW: I Still have a backup and matching passkeys, but the backup is like 10 months old. Would have a newer one but my Signal ended up in a crashing loop and additionally my microSD card died.
This project looks really promising, but I'll loose 2-3 chats with persons I got into Signal in the time between. Is there a way to create a backup from the android files with this?

**Comment by bepaald** [comment]
> This could be mentioned in the readme for cases where Signal is constantly crashing while backups have not been activated beforehand or passkeys have been lost. https://transistor-man.com/restoring_android_signal_from_desktop.html I did not test that, just stumbled upon it.

I'm not sure what you want me to add exactly. As far as I can tell this just describes the `--importfromdesktop` option, which is already in the README. Do you mean to just put a link to that article directly in the README?

> BTW: I Still have a backup and matching passkeys, but the backup is like 10 months old. Would have a newer one but my Signal ended up in a crashing loop and additionally my microSD card died. This project looks really promising, but I'll loose 2-3 chats with persons I got into Signal in the time between. Is there a way to create a backup from the android files with this?

Currently: no. But this is mostly because I've never had access to the 'android files', I suspect that if I did, creating a backup (or importing them into one) would not even be very hard. Do you actually have access to the android files? Are they encrypted? If so, maybe if you tell me how I could get something implemented (in the future).

Thanks!

**Comment by DeathDragonAW** [comment]
> I'm not sure what you want me to add exactly. As far as I can tell this just describes the `--importfromdesktop` option, which is already in the README. Do you mean to just put a link to that article directly in the README?

Not exactly, this also seems to be a solution for the missing contacts issue. 
_"It's important at this point to allow this "new" install access to your contacts, as those contacts get matched up to the contacts from your desktop backup."_


> Do you actually have access to the android files?
Sadly no, tried to access them in different ways but all of those did not work. Gonna discard this idea as I wan't able to use Signal mobile for a time long enough already and will most probably try combining your backup tool with the workaround from the other tutorial.

**Comment by bepaald** [comment]
>Not exactly, this also seems to be a solution for the missing contacts issue.
"It's important at this point to allow this "new" install access to your contacts, as those contacts get matched up to the contacts from your desktop backup."

I don't think I will be adding anything specifically from this article to the readme. The general usage of `--importfromdesktop` is sufficiently documented I think. The rest of the article is mostly things that are implied (you need a backup, yes, this tool is called 'signalbackup-tools' for a reason), or guesswork or even incorrect. Now I may be wrong about this, but as far as I know, at least in recent versions of Signal, allowing Signal access to your contacts is neither required nor sufficient to get the contacts in your backup. The ways I know contacts are added to Signal is by:
- exchanging messages
- restoring a backup (that contains the backups)
- having a PIN set and entering it in Signal upon registration. Not sure about this last one, but I believe this restores data from Signal servers which includes contact information.

It's still a useful article of course, anything to get people aware of the option to get their messages back.

>Sadly no, tried to access them in different ways but all of those did not work. Gonna discard this idea as I wan't able to use Signal mobile for a time long enough already and will most probably try combining your backup tool with the workaround from the other tutorial.

Let me know if you run into any problems or need help.

Thanks again!

**Comment by DeathDragonAW** [comment]
> Let me know if you run into any problems or need help.
Not sure where so I guess I'll simply go on here? 😅

Does this tool not check for duplicates / already existing messages and/or attachments? At first I combined my old android backup (7.8GB) with my desktop (16.3GB) and received a 22.8GB big backup file which I already thought was suspicious but I was not sure. Most of the android backup content should already be included in the desktop files.

But later I created a new backup when I added all missing contacts and tried the same again. My now after some cleanup still 18.4GB android backup combined with my desktop again gave me a 32.8GB file which which is far too big in any case. 
It will also cause logistic issues in my phone with such dimensions 🫠

**Comment by bepaald** [comment]
>Does this tool not check for duplicates / already existing messages and/or attachments?

No it does not, determining duplicates is not precisely possible between the databases (timestamps of messages are not necessarily identical, you really have only the message body to go on, but these can often be identical (for example empty messages with only an attachment)).

To limit which messages are imported into the backup, use the `--limittodates` or `--autolimitdates` options [as mentioned in the README](https://github.com/bepaald/signalbackup-tools?tab=readme-ov-file#desktop).

Also, I can recommend inspecting the generated backup with `--exporthtml` if you have the disk space, that way you now if you got the expected result before attempting to restore on a phone.
