### ISSUE TITLE
Linux decyptKey not working

### ISSUE THREAD

**Issue by robertaramar** [bepaald/signalbackup-tools#248]
I'm using Signal-Desktop 7.27.0 and the current master of this repo.
When trying to execute a --dumpdesktopdb, I get two errors:
```
signalbackup-tools (/home/rschneid/src/Signal/signalbackup-tools/build/signalbackup-tools) source version 20241003.205651 (SQlite: 3.45.1, OpenSSL: OpenSSL 3.2.2 4 Jun 2024)
[Error]: Decryption appears to have failed (padding bytes have unexpected value)
[Error]: Decryption appears to have failed (padding bytes have unexpected value)
```
Can someone confirm whether that is supposed to work? Code fails in https://vscode.dev/github/bepaald/signalbackup-tools/blob/master/desktopdatabase/decryptkey_mac_linux.cc#L117

**Comment by bepaald** [comment]
Hi, thanks for your report. Just a very quick message from my phone since I'm not at home at the moment.

> Can someone confirm whether that is supposed to work?

I can confirm this is supposed to work.

Could you:
- give some details about your system? The code to retrieve the required keys is different for every os, and on Linux even between different desktop environments.
- re run your command with `--vervose` and `--dbusverbose` added? And send me the output (look through it if you feel you need to censor any of it) 

Lastly, can I assume Signal Desktop is still working, that is, it can still open the database correctly? 

Hopefully with this info I can figure out what's happening here when I get home tomorrow. 

Thanks!

**Comment by bepaald** [comment]
One more possibly stupid question if you don't mind: Did it actually work?

Looking at the code, those two errors can not be the last things printed. They are actually not necessarily fatal errors (I will change them to warnings shortly). As multiple possible secrets obtained from the keyring can be tried.

If all secrets were tried and failed, the error should have propagated and the next line would be `"Failed to decrypt valid key. :("`. However, it is possible after these two failed attempts, a third attempt was successful and the next line would show `"Saved database to file '(filename)'"`.

Full output would be appreciated here. With the previously mentioned verbose flags while you're at it. You can save the programs output to a file by adding `--logfile (output.log)` to the command line if needed.

Thanks!

**Comment by bepaald** [comment]
>I just figured what you said, those are only warnings, the decrypting of the database works indeed. Sorry for the confusion.

No problem, thank you for reporting, I understand the errors were confusing. I have made some changes this morning to make the process slightly more clear (turned the errors into warnings unless it fails on the last available secret, and altered the exact text a little). Hopefully that helps a little. I may make more adjustments later, but for now I consider this issue solved.

Let me know if I can do anything else in the future.

Thanks again!

**Comment by robertaramar** [comment]
Hi,

I'm considering to implement a backup2desktopDB functionality into
signalbackup-tools.

I'm wondering if you ever played with that thought and what you think
about doing that.

My motivation is based out of the fact that I lost my Signal Desktop
database due to some bug in a recent flatpak version of SignalDesktop
and I'm pretty mad that this made me loose my whole history on my desktop.

Would you be willing to foster that idea?

Regards,

Robert

--
Robert Schneider
