### ISSUE TITLE
Try to save files with correct extension 2

### ISSUE THREAD

**Issue by jathri** [bepaald/signalbackup-tools#251]
Hello,
great tool that works (using https://github.com/bepaald/signalbackup-tools/commit/7e5242bace2b469fcd037ac910116919347bf5a6 with --exporthtml option). My only problem is similar like in https://github.com/bepaald/signalbackup-tools/issues/232. It is that some files are saved with a .bin extension. And basename is in format: Attachment_1_-1. But I can see that whole filename is present in html file (like Attachment 'search.json.mozlz4'). Can signalbackup-tools_win be improved so as the files are saved with the name from chat? Can attach screens if needed.

**Comment by bepaald** [comment]
Hi!

While it is technically possible to do this, it would be a _lot_ of work. The output of the tool when exporting to directory is meant as a more or less literal representation of the backup contents. It can be read back by the tool to create a valid Android backup file again. Changing the filenames would make this process much, much more difficult. And then there is the problem of duplicate filenames, you might end up with `image.jpg` and `image (2).jpg`, and ten more similarly named files. The tool would need to somehow figure out which file is the one that corresponds to a specific message. 

What is the use-case here? Generally when exporting a backup file to directory, one would work with the SQL database that is exported. This can then be used to match the attachments to certain messages (and filenames), all this info is in the database. If you just want to save the media from the backup, but do not want the HTML to be generated, maybe try `--dumpmedia`? Does that do what you want?

Thanks!

**Comment by jathri** [comment]
Hello, I do not believe that html exports are used for creating backup files again. There are better formats for that. Html exports are used for convenienece (to read info comfortably). And part of this convenience package could be real names of files. Note: It is just feature proposal. Perhaps new parameter could be added (to export files with real names). For the users who do not care about creating backup files back again. But I respect the argument that it would be a lot of time or that the priority for this is low.

**Comment by bepaald** [comment]
O sorry, I think I misunderstood your initial message. I'll take a better look at it when I get home later today.

**Comment by bepaald** [comment]
Ok, apologies again, in my initial reply for some reason I had gotten it in my head you wanted original filenames for attachments when exporting the raw backup to directory (not HTML export, but just `signalbackup-tools [input] [passphrase] -o OUTDIR/`).

For the HTML export, the reason for the current file naming scheme is that using the original filenames would break the `--append` option (which is quite useful). But I have no problem adding a switch for using the original filenames, which then also disallows `--append` (will only work with `--overwrite`, or an empty output directory). Not sure when I'll get to it, but I'll give it a go and report back here when i have something to test.

Thanks!

**Comment by bepaald** [comment]
I believe this feature is done. The option is `--originalfilenames`. When this option is supplied, the directory passed to `--exporthtml` must either be empty, non-existing, or `--overwrite` must also be supplied.

Please test it and let me know if it behaves as you'd expect.

Thanks!

**Comment by jathri** [comment]
Yes, it works exactly like it should :) Many thanks!
