### ISSUE TITLE
No Issues, just a big thank you!

### ISSUE THREAD

**Issue by h0st1le** [bepaald/signalbackup-tools#257]
This software made it possible to assemble a single chat history from some random backups, and about 5 aging phones, i simply never cared enough to backup and standardize, I've now got a clean history, tidied up my contact list, setup sync, and will never be in that situation again. Absolute champion man!
Cheers!

**Comment by bepaald** [comment]
That is great to hear, thanks for the feedback!

**Comment by neuhaus** [comment]
I came here to say **_thank you_** also, I also sent you a donation (btw I noticed you have some bitcoins in your wallet, in case you haven't noticed). Awesome stuff!

One suggestion: Is there a way to get all the command line parameters without having to run the app? They don't seem to be all in the README (which is already long enough as-is).
(I ran `signalbackup-tool --help` and pasted the output at https://pastebin.com/h02ctZ1c )
