### ISSUE TITLE
[MacOS] instant crash due to "regex_error"

### ISSUE THREAD

**Issue by Sab44** [bepaald/signalbackup-tools#259]
Hi,
I'm getting 
```
➜  ~ signalbackup-tools
libc++abi: terminating due to uncaught exception of type std::__1::regex_error: The expression contained an invalid escaped character, or a trailing escape.
[1]    8431 abort      signalbackup-tools
```
right away when I try to execute the tool, it does not matter if / what arguments I provide.
Currently running on M1 Macbook Pro with MacOS 14.7.1.

I installed it successfully by following the instructions for the installation via homebrew.
Install log:
```
➜  ~ brew install --HEAD --formula Documents/signalbackup-tools.rb
==> Fetching dependencies for signalbackup-tools: cmake, openssl@3 and sqlite
==> Fetching cmake
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/manifests/3.30.5
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/blobs/sha256:d9ed9f9fdeae
######################################################################### 100.0%
==> Fetching openssl@3
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/manifests/3.4.0
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/blobs/sha256:706b2f22
######################################################################### 100.0%
==> Fetching sqlite
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.47.0
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:3c1e59085e1
######################################################################### 100.0%
==> Fetching signalbackup-tools
==> Cloning https://github.com/bepaald/signalbackup-tools.git
Cloning into '/Users/username/Library/Caches/Homebrew/signalbackup-tools--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Installing dependencies for signalbackup-tools: cmake, openssl@3 and sqlite
==> Installing signalbackup-tools dependency: cmake
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/manifests/3.30.5
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/8ab8d3df0588546d97c0c109b22526e4a1841811d7939fc717ecfe13c6144add--cmake-3.30.5.bottle_manifest.json
==> Pouring cmake--3.30.5.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/cmake/3.30.5: 3,424 files, 55.3MB
==> Installing signalbackup-tools dependency: openssl@3
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/manifests/3.4.0
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/a8a169d38329b14f967d497d0ea77eee6dc5444175093fc7b26026b357e81736--openssl@3-3.4.0.bottle_manifest.json
==> Pouring openssl@3--3.4.0.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/openssl@3/3.4.0: 7,236 files, 33.4MB
==> Installing signalbackup-tools dependency: sqlite
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.47.0
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/2acd26e317f3463995d9c8df6d1f6660834a2adccf6448e6166f34a89d607683--sqlite-3.47.0.bottle_manifest.json
==> Pouring sqlite--3.47.0.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/sqlite/3.47.0: 12 files, 4.9MB
==> Installing signalbackup-tools --HEAD
==> cmake -B build
==> cmake --build build
🍺  /opt/homebrew/Cellar/signalbackup-tools/HEAD-2d9b4c9: 6 files, 3.3MB, built in 37 seconds
==> Running `brew cleanup signalbackup-tools`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

**Comment by bepaald** [comment]
Thanks for the report, I was able to reproduce.

I suspect this is to do with `libc++` poor regex implementation (not sure yet). I will try to pinpoint the problem later and fix it. Unfortunately, I think the problem is somewhere in a huge monster of a regex ([this one](https://github.com/bepaald/signalbackup-tools/blob/master/signalbackup/statics_linkify.cc)). I might end up just disabling linkifying in htmlexport on macOs.

Anyway, enough speculation, I need to investigate first. I'll get back to you. Thanks again!

**Comment by bepaald** [comment]
After some trial and error, it seems libc++ does not like the few escaped underscores in the regex (`\\_`). Since the underscore does not need to be escaped in regex anyway, I just replaced them with `_`, and at least on my (virtual) macos machine, the problem is gone.

Please update, test, and let me know if it is fixed. Thanks!

**Comment by Sab44** [comment]
Working perfectly fine now! Thanks for dealing with this so quickly.
The result is absolutely amazing, thanks for this great tool.

Just a sidenote, the upgrade process did work but it seems the homebrew setup could be improved. But that's really minor so just a nice-to-have I guess.
Upgrade log:
```
➜  ~ brew upgrade --fetch-HEAD Documents/signalbackup-tools.rb
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
Error: Failed to load cask: Documents/signalbackup-tools.rb
Cask 'signalbackup-tools' is unreadable: wrong constant name #<Class:0x0000000145037a00>
Warning: Treating Documents/signalbackup-tools.rb as a formula.
==> Upgrading 1 outdated package:
signalbackup-tools HEAD-2d9b4c9 -> HEAD-98ea553
==> Fetching signalbackup-tools
==> Cloning https://github.com/bepaald/signalbackup-tools.git
Updating /Users/sabri/Library/Caches/Homebrew/signalbackup-tools--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 98ea553 libc++ does not like escaped underscores (#259)
==> Upgrading signalbackup-tools
  HEAD-2d9b4c9 -> HEAD-98ea553
==> cmake -B build
==> cmake --build build
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################### 100.0%
🍺  /opt/homebrew/Cellar/signalbackup-tools/HEAD-98ea553: 6 files, 3.3MB, built in 42 seconds
==> Running `brew cleanup signalbackup-tools`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/signalbackup-tools/HEAD-2d9b4c9... (6 files, 3.3MB)
```

**Comment by bepaald** [comment]
> Working perfectly fine now! Thanks for dealing with this so quickly.
> The result is absolutely amazing, thanks for this great tool.

Great! Glad it's working.

>Just a sidenote, the upgrade process did work but it seems the homebrew setup could be improved. But that's really minor so just a nice-to-have I guess.

I suppose you're talking about this part?
```
Error: Failed to load cask: Documents/signalbackup-tools.rb
Cask 'signalbackup-tools' is unreadable: wrong constant name #<Class:0x0000000145037a00>
Warning: Treating Documents/signalbackup-tools.rb as a formula.
```

Those messages (not sure if it is an error, or a warning, looking at the output it seems homebrew isn't sure either :-)), can be easily inhibited by explicitly telling brew it's dealing with a formula by adding `--formula` (just like in the installation command). I've updated the README to reflect this. Also, I _think_ you don't need the actual formula file anymore, you can just do `brew upgrade --fetch-HEAD --formula signalbackup-tools`.

Did you have any other problems with the upgrade besides those lines? I have to admit I'm not really at home on Apple systems, so if you have any simple improvements/suggestions, I don't mind hearing them.

Thanks again for your report!

**Comment by Sab44** [comment]
You are right. Using `brew upgrade --fetch-HEAD --formula signalbackup-tools` all went through smoothly. No other problems besides this, and with the updated README I think everyone should be fine.

Regarding Apple systems, the homebrew setup is very much appreciated, considering that almost everyone I know who uses MacOS professionally (mostly in a software-engineering context to be fair) makes use of homebrew.
What caused me a bit of confusion is the fact that it is rather unusual to have a formula file that needs to be downloaded and then run the homebrew install command against this downloaded file. It took me a minute to understand that this is what I'm supposed to do. Potentially, you could make this clearer, e.g. change

> A homebrew formula is provided in [homebrew/signalbackup-tools.rb](https://raw.githubusercontent.com/bepaald/signalbackup-tools/master/homebrew/signalbackup-tools.rb). On modern macOS versions...

to something like 

> A homebrew formula is provided in [homebrew/signalbackup-tools.rb](https://raw.githubusercontent.com/bepaald/signalbackup-tools/master/homebrew/signalbackup-tools.rb). Download this file to your machine. Then, on modern macOS versions...

Also, looking at the `signalbackup-tools.rb` file, looks like it has a `test` block which executes `signalbackup-tools --help`. Thinking about the original regex issue, I feel like this test should have failed, presumably failing the installation straight away. So maybe there could be some small adaptation in that test block to check whether the output of this command is as expected / contains some expected string like  maybe `Usage: signalbackup-tools`.

All of this is the cherry-on-the-top now for this software, very appreciated, thanks again!

**Comment by bepaald** [comment]
> You are right. Using `brew upgrade --fetch-HEAD --formula signalbackup-tools` all went through smoothly. No other problems besides this, and with the updated README I think everyone should be fine.

Good!

> Regarding Apple systems, the homebrew setup is very much appreciated, considering that almost everyone I know who uses MacOS professionally (mostly in a software-engineering context to be fair) makes use of homebrew. What caused me a bit of confusion is the fact that it is rather unusual to have a formula file that needs to be downloaded and then run the homebrew install command against this downloaded file. It took me a minute to understand that this is what I'm supposed to do. Potentially, you could make this clearer, e.g. change
> 
> > A homebrew formula is provided in [homebrew/signalbackup-tools.rb](https://raw.githubusercontent.com/bepaald/signalbackup-tools/master/homebrew/signalbackup-tools.rb). On modern macOS versions...
> 
> to something like
> 
> > A homebrew formula is provided in [homebrew/signalbackup-tools.rb](https://raw.githubusercontent.com/bepaald/signalbackup-tools/master/homebrew/signalbackup-tools.rb). Download this file to your machine. Then, on modern macOS versions...

Done!
 
> Also, looking at the `signalbackup-tools.rb` file, looks like it has a `test` block which executes `signalbackup-tools --help`. Thinking about the original regex issue, I feel like this test should have failed, presumably failing the installation straight away. So maybe there could be some small adaptation in that test block to check whether the output of this command is as expected / contains some expected string like maybe `Usage: signalbackup-tools`.

I had been thinking that as well. As it turns out, homebrew doesn't actually run the test when installing (if I understand correctly). One needs to manually run `brew test signalbackup-tools` to do that. I have changed my [Github action](https://github.com/bepaald/signalbackup-tools/blob/master/.github/workflows/test-macos-build.yml) to run the test after building, so at least _I_ will get notified if a commit breaks the program.

> All of this is the cherry-on-the-top now for this software, very appreciated, thanks again!

Thank you for your helpful comments!
