### ISSUE TITLE
Search results display wrong date and time

### ISSUE THREAD

**Issue by Sab44** [bepaald/signalbackup-tools#260]
Hello again,
I have successfully exported some chats with
```
signalbackup-tools signal-xxx.backup 123456 --exporthtml html-backup --themeswitching --limittothreads 2,7 --searchpage
```
and it's all working fine, there's just a minor flaw: when searching for chat messages in the searchpage, the time and date is not displayed correctly.
E.g. in the chat, the message timestamp is `Jan 20, 2021 16:02:45` which is correct. Searching for that message, the result in the search page displays timestamp `Aug 9, 1976, 00:05:30` (notice also the minor difference in formatting, here's an additional `,` after the year). Clicking on the message forwards to the correct message in the chat and there everything is displayed fine.

Ran this command on MacOS 14.7.1 (M1 MacBook Pro).

Thanks!

**Comment by bepaald** [comment]
Thanks for this one, should be fixed. And I took care of that comma while I was at it (date formatting in javascript is not a nice experience btw).

Let me know if it's fixed. Thanks!
