### ISSUE TITLE
This app is not compatible with your computer - PowerShell doesn't help!

### ISSUE THREAD

**Issue by bjjnpy** [bepaald/signalbackup-tools#261]
Hello,
I've also tried to restore chats according to the manual linked in #247 issue. I've got the same error message as @viiktr ("This app is not compatible with your computer").
Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
System type: 64-bit operating system, x64-based processor.
Tried to use 

> .\signalbackup-tools_win.exe [backup file name] [your code] --importfromdesktop --output [new_database_output]

 command in PowerShell but not worked.

![signal](https://github.com/user-attachments/assets/85130d33-781e-4c57-ab76-02455608aea6)

What am I doing wrong?

_Originally posted by @bjjnpy in https://github.com/bepaald/signalbackup-tools/issues/247#issuecomment-2461885896_

**Comment by bepaald** [comment]
Hi! Honestly I have no clue. I strongly feel this is not a problem with this program, but something on your computer, you are probably better off asking this on a Windows help forum.

The only thing I can think of is that the download is corrupted? Maybe you could check the MD5 sum:
```
Get-FileHash C:\signal_fix\Signal\signalbackup-tools_win.exe -Algorithm MD5
```

Just for the record, here is a screenshot of the program running fine on a vanilla Windows 11 install in PowerShell:

![Screenshot_07_11_2024_15_27_27](https://github.com/user-attachments/assets/2edb8747-325b-4606-a995-9b122bf7af49)

(and it works perfectly fine in cmd as well). Could you compare the MD5 sum in that screenshot to yours? If it's different, try re-downloading the program (and check the hash again).

Thanks!

**Comment by bjjnpy** [comment]
Hi, thanks, now it works fine!
