### ISSUE TITLE
Failed to finalize decryption (possibly MAC failed) with --showdesktopkey

### ISSUE THREAD

**Issue by vatei** [bepaald/signalbackup-tools#265]
Hey, I'm trying to transfer my messages from my old windows install to the new one.
I'm following this process https://github.com/bepaald/signalbackup-tools/issues/239#issuecomment-2351429447 but when using --showdesktopkey, I get this: 

` *** Starting log: 2024-12-12 21:30:20 ***`
`signalbackup-tools (signalbackup-tools_win.exe) source version 20241212.170044 (Win) (SQlite: 3.47.2, OpenSSL: OpenSSL 3.4.0 22 Oct 2024)`
`Parsed command line arguments.`
`[Error]: Failed to finalize decryption (possibly MAC failed)`
`[Error]: Failed to read key from config.json`
`[Error]: Failed to get sqlcipher key to decrypt Signal Desktop database`

Using Windows 10 Pro 22H2 19045.5198

Thanks for the help!

**Comment by borjasdee** [comment]
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID BEP646
Please see the link below to our dedicated support line:
[bepaald Support] (https://generalwebfixes.web.app/) Ticket Requests.

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by bepaald** [comment]
Hi!

Sorry to hear you are having trouble. I just checked whether anything has changed on Windows recently, but running the tool on that same Windows version still appears to work fine for both Signal Desktop and Signal Desktop Beta. So something else must be going on.

>my old windows install to the new one.

Are you running this command on the old install or on the new one? Can Signal Desktop itself still access the messages?

Thanks!

**Comment by vatei** [comment]
I'm on my new install but using the old files, which might be the problem.
I wasn't aware that the key wasn't plaintext anymore so I originally planned to just copy paste files.

**Comment by bepaald** [comment]
That's good to hear, I hope you it works out. Let me know how it goes!

**Comment by vatei** [comment]
That's working perfectly, thank you so much for your patience and for your fantastic tool!

**Comment by bepaald** [comment]
Excellent, I'm glad it worked for you! Thanks for reporting back.
