### ISSUE TITLE
Backupfile created with this tool cant be restored

### ISSUE THREAD

**Issue by newhinton** [bepaald/signalbackup-tools#3]
I am trying to migrate signal to a different phone, but backups created by signal are broken. Therefore i tried to recover the backupfile with this tool. It works, i can properly decrypt the file (If i inspect the sqlite file, everything seems reasonable complete)

However, if i try to rebuild the file with the same password, it strips basically every attachment (8mb instead of ~220mb)

That is fine, i still can archive the attachments since they are beeing decrypted. Sadly, the new file wont restore. The only difference is that now signal recognizes my 4000 messages but continues to fail after that (With reporting that i have used a wrong password)

Any suggestions why this fails?

The tool you wrote works wonders, i have now access to my data, but getting it back into signal would be amazing.

I can provide logs if you need them

**Comment by bepaald** [comment]
No idea why it fails no. These are always hard problems to diagnose, it's very tough trying to recreate all the things that can happen if you feed random data to a program. And depending on exactly what data is corrupted, it is possible the file is simply beyond repair (though I'm still waiting to see the first real case of that). But anyway, let's see if we can find out what is happening.

If I understand correctly, you used the tool to decrypt the database to separate files in a directory? Did it say anything about encountering a bad mac during decryption? I would have guessed the intermediate step of saving to directory does not make a difference, but just to make sure, could you just run the tool on the broken database as described in the readme? That is, without the intermediate step:

```
signalbackups-tools [input backupfile] [password] --output [newbackupfile] --opassword [newpassword]
```

And please post as much of the output as you feel comfortable with (but at least replace any phone numbers with X's). Is the file created this way also only 8Mb? If you run the tool again on the newly created file (you can just omit the `--output` flag), does it give any errors, or does it just run up to 100% without problems?

**Comment by newhinton** [comment]
I could recreate the issue with a new setup. However, it seems you are right. If i skip the intermediate step, i can properly restore the file. If i pack it from a folder, it fails. I can now fully restore everything, including mediafiles. Thank you for your tip with the intermediate!

**Comment by bepaald** [comment]
Ok, thanks, I'm happy that you have your backup fixed!

Still if you consistently get a broken backup by packing a folder up that is still a (different) bug. I can not seem to reproduce that: both with good and broken backup files, backups built from an intermediate folder or in one go are always identical. Did you do anything with the backup files in between decrypting and re-encrypting? Did you open the sqlite db, and run any commands? Does the tool in its output give any errors or warnings?
