### ISSUE TITLE
Extracting attachements

### ISSUE THREAD

**Issue by Japhys** [bepaald/signalbackup-tools#30]
At the risk of being an idiot, but is it possible to extract media with this tool asl well? I managed to export to csv en xml so I am perfectly happy.

I did manag to extract media with Signal-back tool but that one was giving me problems with the xml. So after using both I was pretty much everything I need. 

But still wondering if your tool is doing media as well?

**Comment by bepaald** [comment]
Well, yes it does, but not in a really user-friendly way...

When you specify an output directory (as opposed to a file) the program will dump all the frames and attachments in the backup to that directory decrypted (so: `signalbackup-tools [input] [password] -o [directory]`). But the attachments are just all there named after their internal id's so the program can actually repack everything into a working backup again.

I do plan on actually providing a `--dumpmedia` option. I think it should then make a subdirectory for each conversation, use the original filename (where available) and set the proper creation date on each attachment. It should be quite easy to implement, I could easily have it done before the end of the week if I can find some time. What do you think? Any specific ideas on how this should work before I start writing the code?

I'll leave this issue open so I can post an update if it's done. Thanks!

**Comment by Japhys** [comment]
Thanks for your reply, I have been so busy I missed it :)

**Comment by bepaald** [comment]
So, I've just added the option to save all media. Running `signalbackup-tools [input] [password] --dumpmedia [outputfolder]` should do the trick. Optionally add `--limittothreads 1,2,3-8,16` to limit to thread(ranges), the threads can be listed by `--listthreads`. I'll update the readme sometime soon.

It was a bit more complicated than I thought it would be, with duplicate filenames, updating timestamps and determining the proper file extensions for given mime types, but I hope it works ok.

**Comment by Japhys** [comment]
That is wonderful. Thanks very much. I am going to give it a try this weekend!

**Comment by Meteor0id** [comment]
--dumpmedia should be documented in readme
