### ISSUE TITLE
Feedback on the merge function

### ISSUE THREAD

**Issue by InfinityPhoenix** [bepaald/signalbackup-tools#31]
I ran the merge function as detailed in the documentation and it worked perfectly! For reference, the two database versions I merged were from versions 80 and 89 respectfully.

**Comment by bepaald** [comment]
Thanks for you feedback! I'm happy it worked.

Just to be sure, I'm currently still tracking two possible issues with merging mentioned in https://github.com/bepaald/signalbackup-tools/issues/27#issuecomment-789256441. Maybe you would be so kind to confirm if possible?

1. Voice notes from the imported threads do not play. They can be saved (and then played externally) and the waveform-graphic is generated, but playing them inside the app fails. If you have any voice notes, could you check this?
2. When inside a conversation, going to the menu and selecting 'all media', the media from the imported threads are not shown. They are still shown in the conversation as usual, but not in the media-overview.

I do not expect you to have these issues, i can't reproduce them myself, but if you could let me know whether you are seeing these problems or not I would be grateful.

Thanks!
