### ISSUE TITLE
Unexpected end

### ISSUE THREAD

**Issue by Aushilfsarnie** [bepaald/signalbackup-tools#33]
Hello, thanks for great tool, but in Windows it ends in my progress always like following:
Frame number: 27945
        Size: 10
        Type: SHAREDPREFERENCEFRAME
         - (file  : "
 There it hangs and hangs...please telle me, what to do. Thanks!

**Comment by bepaald** [comment]
I have no idea what is going on, never seen that behavior before. Generally it should not actually output these frame-details unless somehting is wrong. Could you give a little bit more context? The exact command you are running and some more of the output? At least a couple dozen lines before this happens?

**Comment by bepaald** [comment]
Closing just to clean up and for lack of information. If you're still having issues, feel free to open a new issue.
