### ISSUE TITLE
The Windows exe is skipping attachments while decrypting 

### ISSUE THREAD

**Issue by trevdan88** [bepaald/signalbackup-tools#34]
Observed that the Windows.exe is skipping attachments while decrypting export from database version 90 (latest signal on Android)

also tried the latest Windows release still same issue.

**Comment by trevdan88** [comment]
Hi please could you let me know when you have some time

thank you in advance

**Comment by bepaald** [comment]
I'm not sure what you mean. What function are you running exactly, could you show me the command and the full output?

**Comment by trevdan88** [comment]
@bepaald 

C:\xx>signalbackup-tools_win.exe --output signal_backup\ test.backup XXXXXXXXXXXXXXXXXXXXX0XXXXXXXX
signalbackup-tools (signalbackup-tools_win.exe) source version 20210413.213920 (OpenSSL)
IV: (hex:) xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx (size: 16)
SALT: (hex:) xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx (size: 32)
BACKUPKEY: (hex:) xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx (size: 32)
CIPHERKEY: (hex:) xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx (size: 32)
MACKEY: (hex:) xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx (size: 32)
COUNTER: 3100034000
Reading backup file...
FRAME 950 (100.0%)... Read entire backup file...

done!

Exporting backup into 'signal_backup\'
Writing HeaderFrame...
Writing DatabaseVersionFrame...
Writing Attachments...
Writing Avatars...
Writing SharedPrefFrame(s)...
Writing KeyValueFrame(s)...
Writing StickerFrames...
Writing EndFrame...
Writing database...
Done!

There were no errors during execution but the output directory has missing attachment entries:
Attachment_01_000000001.bin
Attachment_01_000000001.bin
_<MISSING>Attachment_02_000000003.bin
<MISSING>Attachment_02_000000003.sbf_
Attachment_03_000000004.bin
Attachment_03_000000004.sbf
Attachment_04_000000005.bin
Attachment_04_000000005.sbf
Attachment_05_000000011.bin
Attachment_05_000000011.sbf
Attachment_06_000110000.bin
Attachment_06_000110000.sbf
Attachment_07_000000470.bin
Attachment_07_000000470.sbf
Attachment_08_001234000.bin
Attachment_08_001234000.sbf
_<MISSING>Attachment_09_000004400.bin
<MISSING>Attachment_09_000004400.sbf_

I opened the the SQLite DB to check if the records exist under the PART table, and they appeared to be present 

They are 1 x PDF & 2 x JPG files

**Comment by trevdan88** [comment]
@bepaald I think I figured it out.

These appear to be attachments that were not downloaded.

A log of such files that failed to export would be a good feature to include.

Hoping that this comment would help else.

**Comment by bepaald** [comment]
I read your previous message while at work and already thought this was what you were seeing. Now that I'm home, I see you have figured it out already. 

When exporting to file, there is actually already a warning in place: https://github.com/bepaald/signalbackup-tools/blob/9e9f0d12f08e46b5e8e5fbb9163c5d9e463b6583/signalbackup/exporttofile.cc#L176

I will consider implementing the same for the dir output, however:
1. It is not as straightforward to implement for the the dir-export as it is for the file-export
2. I've actually had quite a few alarmed questions about the warning, even though nothing is actually wrong and no action can (and needs) to be taken. I've often actually thought about removing it.

BTW. If you only use the export-to-dir to get your attachments, you might be interested in the new (undocumented and poorly tested) `--dumpmedia [DIR]` option. It will (attempt to) place the attachments in folders for each conversation, give it the original name and set the original timestamp.

Thanks for your bug report! I wish they were all this easy :)
