### ISSUE TITLE
Disappearing Messages are not available in the decrypted database

### ISSUE THREAD

**Issue by trevdan88** [bepaald/signalbackup-tools#35]
So I got a disappearing message today which expires in 6 days from today, so I created a backup of it today and tried decrypting the data, but the message does not appear in the database. Is this expected?

Does the signal export include disappearing messages in their android backup?

**Comment by bepaald** [comment]
I'm sorry, but signal does _not_ include disappearing messages (or view-once media) in the backup (https://github.com/signalapp/Signal-Android/blob/b053fbc4a7aa9ace749df20045706424f0713205/app/src/main/java/org/thoughtcrime/securesms/backup/FullBackupExporter.java#L142). There is nothing I can do about that. You could consider running a custom build to prevent this in the future, but it won't help you with your current problem. As far as I know there is nothing you can do to save the message apart from taking a screenshot. Good luck!

**Comment by trevdan88** [comment]
Does it work if we turn off disappearing messages and then try the export?

does the setting at time of receipt of the message / media matter?

**Comment by bepaald** [comment]
As far as I know you can not change the disappearing nature of a message retroactively, changing the setting will only affect newly sent messages. But that's a Signal thing, I'm not 100% sure about it, you would need to test be certain.
