### ISSUE TITLE
extracting only profile image

### ISSUE THREAD

**Issue by 001101** [bepaald/signalbackup-tools#39]
hello,

i want to simply extract the current profile image, unfortunately it is not included in the backup or just simply on filesystem and still can not any hint about where it is stored, does someone know how to get the picture?

thanks in advice & best wishes

**Comment by bepaald** [comment]
The avatars are in the backup, you can get them by calling `signalbackup-tools [file] [password] --dumpavatars [outputdirectory]`. Optionally you can get the avatar only for contacts 'John Doe' and 'Jane Doe', by adding `--limitcontacts "John Doe","Jane Doe"` (notice no space between the list items).

This option was just added, so get the newest version to use it.

Not sure if this solves your problem. Please let me know so I can close this issue or help you another way.
