### ISSUE TITLE
Newest windows executable doesn't launch

### ISSUE THREAD

**Issue by saburai7** [bepaald/signalbackup-tools#41]
Apologies if I'm just doing something wrong, but after downloading the latest Windows executable, which I believe was released yesterday, I just get an error: 

C:\Users\ ... \Phone backups>signalbackup-tools_win.exe [signal-2021-08-10-00-22-45.backup] [54...password...74] --exportxml [dht.xml]
signalbackup-tools (signalbackup-tools_win.exe) source version 20210809.171715 (OpenSSL)
Failed to open file: '[signal-2021-08-10-00-22-45.backup]'
Failed to create filedecrypter
Failed to open backup

**Comment by bepaald** [comment]
Hi, no problem. I think you will want to remove the brackets `[` and `]` :)

Let me know how the exportxml function works, there have been some changes to Signal's internal database which forced me to fix some issues, but I haven't (thoroughly) tested this function since.

**Comment by saburai7** [comment]
Thanks, that worked like a charm. The XML looks great--I just need to try to import it to my SMS.

**Comment by bepaald** [comment]
Great. Thanks!
