### ISSUE TITLE
Feedback on successful backup merge

### ISSUE THREAD

**Issue by BeckerFelix** [bepaald/signalbackup-tools#42]
I was in desperate need to merge two Signal backups and am thus extremely grateful for your tool! :heart: 

Merging two backups with db versions 105 and 112 failed at first with `no such column: thread_recipient_id`. It was however obvious that this is a database issue. When I imported the first one into Signal and rewrote the backup with db 112, merging worked like a charm.
* searching through conversations works
* "all media" works
* I don't have any voice messages, so I can't test those

**Comment by bepaald** [comment]
Hey thanks for reporting!

Yeah, usually a difference of a few db versions doesn't matter much, but every once in a while they change something big, making them incompatible. That just happened to be at version 108, so you were very correct to update the older db.

Happy everything worked out, and thanks again for letting me know!
