### ISSUE TITLE
Switch sender and recipient in one-on-one conversation

### ISSUE THREAD

**Issue by bepaald** [bepaald/signalbackup-tools#44]
I am busy too, so it's not a problem. Thanks a lot for your answer. Maybe there is a way to completely reverse all the messages in the friend's backup and then cropping the backup? I will open an issue here as soon as I have free time. Maybe, if reversing messages is possible in friend's backup, then there is no need to crop it, I'll just have to reverse messages and restore the whole backup. But the question is how I can do that.

_Originally posted by @HiperFall in https://github.com/bepaald/signalbackup-tools/issues/9#issuecomment-905837706_

**Comment by bepaald** [comment]
Yes, if the other database has only one single conversation (with you) then there may not be a need to crop. Though there may be some side effects, for example, restoring your friend's (reversed) backup will also import his entire list of contacts into your Signal. This may not be a problem (and is easily fixable), but I need to think about other possible side effects.

I will get to work on writing a function to reverse messages. It is not as simple as it seems at first. There is also missing information that needs to be filled in. For example, the incoming messages in your friend's backup do not have delivery/read receipts, but when they are turned into outgoing messages they need these. Do you want them marked as received or read?

While I work on this, you could help me out by running this on your friend's backup and posting the results: `signalbackup-tools [input] [password] --runprettysqlquery "SELECT DISTINCT thread_id,type,(type & 0x1f) FROM sms WHERE type & 0x1f IS NOT 20" --runprettysqlquery "SELECT DISTINCT thread_id,type,(type & 0x1f) FROM sms WHERE type & 0x1f IS 20" --runprettysqlquery "SELECT DISTINCT thread_id,msg_box,(msg_box & 0x1f) FROM mms WHERE msg_box & 0x1f IS NOT 20" --runprettysqlquery "SELECT DISTINCT thread_id,msg_box,(msg_box & 0x1f) FROM mms WHERE msg_box & 0x1f IS 20"`

Thanks!

**Comment by HiperFall** [comment]
Hey, thanks! I want them marked as read. 


Yeah, sure. 

Reading backup file...
FRAME 69120 (100.0%)... Read entire backup file...

done!
 * Executing query: SELECT DISTINCT thread_id,type,(type & 0x1f) FROM sms WHERE type & 0x1f IS NOT 20
----------------------------------------
| thread_id | type     | (type & 0x1f) |
----------------------------------------
| 1         | 10485783 | 23            |
| 1         | 16406    | 22            |
| 1         | 1        | 1             |
| 1         | 2        | 2             |
| 1         | 3        | 3             |
| 1         | 7        | 7             |
| 1         | 10       | 10            |
| 1         | 8        | 8             |
| 2         | 10485783 | 23            |
| 3         | 2097156  | 4             |
----------------------------------------
 * Executing query: SELECT DISTINCT thread_id,type,(type & 0x1f) FROM sms WHERE type & 0x1f IS 20
-----------------------------------------
| thread_id | type      | (type & 0x1f) |
-----------------------------------------
| 1         | 10485780  | 20            |
| 1         | 278921236 | 20            |
-----------------------------------------
 * Executing query: SELECT DISTINCT thread_id,msg_box,(msg_box & 0x1f) FROM mms WHERE msg_box & 0x1f IS NOT 20
-------------------------------------------
| thread_id | msg_box  | (msg_box & 0x1f) |
-------------------------------------------
| 1         | 10485783 | 23               |
| 1         | 10485782 | 22               |
| 1         | 10485784 | 24               |
| 2         | 10485783 | 23               |
-------------------------------------------
 * Executing query: SELECT DISTINCT thread_id,msg_box,(msg_box & 0x1f) FROM mms WHERE msg_box & 0x1f IS 20
-------------------------------------------
| thread_id | msg_box  | (msg_box & 0x1f) |
-------------------------------------------
| 1         | 10485780 | 20               |
-------------------------------------------

**Comment by bepaald** [comment]
Excellent, thanks for your patient testing. Glad it worked.

I also just now figured out what these four:
```
Unhandled type: 9924
Unhandled type: 10124
Unhandled type: 10724
Unhandled type: 10824
```

message are. They are messages which failed to send. The function as it was just leaves the messages untouched: so in the switched conversation are now 4 not-switched messages.

There are a few options:
- Just leave them be, because it's no big deal
- Rerun the function, I just pushed a change to handle this message type. The messages that have failed to send are deleted (as they would not have appeared in the receiving database which we are trying to reproduce)
- Manually delete them. If you still have the backup you used to switch the conversation, you could run `./signalbackup-tools [input] [passwd] --runprettysqlquery "SELECT DATETIME(ROUND(mms.date / 1000), 'unixepoch') AS 'date',body FROM mms WHERE (msg_box & 0x1f) IS 24 AND thread_id IS 4"` to show the date and body of the messages to easily find them on the phone (either by date or by searching for the body-text). Judging by the _id's they should be pretty close together.

Thanks again!

**Comment by umglurf** [comment]
Hi, these four did not cause any noticiable issues, but great that you found out what is it and have fixed it. I guess this will help @HiperFall when he is able to test.

**Comment by HiperFall** [comment]
Hi again! I didn't quite understand which commands I have to run to execute these operations correctly. Can you, please, write a short instructions. Thanks in advance!

**Comment by bepaald** [comment]
Hi. It's been a while, but hopefully the following will (still) work:

Given your own (incomplete) backup 'hiperfall.backup' and your friends' backup 'other_backup':

- Optionally crop the 'other.backup' so that messages are not doubled. In the end, we import the entire reversed backup into you own existing backup. If messages appear in both backups, they will be doubled. To prevent this run `signalbackup-tools hiperfall.backup [passwd] --listthreads` to show the dates of the messages in that backup ('Min Date' and 'Max Date'), then crop the other backup to the start date: `signalbackup-tools other.backup [passwd] --croptodates "0-[Min Date]" -o other-cropped.backup`
- Reverse the messages in your friends' backup: `signalbackup-tools other-cropped.backup [passwd] --hiperfall 1 -o other-reversed.backup`.<sup>1</sup>
- Import the reversed backup into your own: `signalbackup-tools hiperfall.backup [passwd] --importthreads 1 -s other-reversed.backup -sp [passwd] -o FINALOUTPUT.backup`.

That should be it. Rename the output file to something Signal will pick up (like signal-2021-01-31-00-00-00.backup) and copy it to the phone. I hope it works, please let me know. If anything goes wrong, please try to be detailed about what happened, which command you ran and what the output was exactly. I hope this is clear, let me know if you have more questions.

**1.** If this ends with _'Failed to determine recipient, please add option to specify backup owners own phone number, for example: `--setselfid \"+31612345678\"''_ you should add this option to the command line, where the phone number is your friends' (not yours). So: `signalbackup-tools other-cropped.backup [passwd] --hiperfall 1 --setselfid "[other-phonenumber]" -o other-reversed.backup`.

**Comment by HiperFall** [comment]
I ran `./signalbackup-tools signal-2022-01-19-00-20-31.backup 513469877487860599939445708649 --hiperfall 1 -o other-reversed.backup`

Output:

`signalbackup-tools (./signalbackup-tools) source version 20220111.170852 (OpenSSL)
IV: (hex:) 5a 89 df 94 22 c3 6f 8a 89 02 a5 b3 7f 25 c1 cf (size: 16)
SALT: (hex:) f2 4e 00 2f 28 b9 d1 61 6f 27 5e 9c bc e3 8a 1d ab 22 1c 7a 44 df 42 fd d9 76 84 32 50 03 33 15 (size: 32)
BACKUPKEY: (hex:) 13 14 7b 98 04 87 7d 51 91 09 8b e1 64 6c 4a cd 9b d9 f6 df 43 d5 3a 0b 9d 74 64 21 16 6d cd d2 (size: 32)
CIPHERKEY: (hex:) 0f 56 42 d1 93 2f 8e e1 9b 20 97 55 48 3d d2 e2 73 b8 69 32 ba 04 f3 bf 54 53 8e b3 48 4e 2c 16 (size: 32)
MACKEY: (hex:) 12 e4 9e 59 9b e7 23 46 a0 3d a2 5a 3f de a7 ed 15 34 ab 63 0d 73 12 56 30 24 e2 ed ef af 62 d2 (size: 32)
COUNTER: 1518985108
Reading backup file...
FRAME 122861 (100.0%)... Read entire backup file...

done!
Got recipients: 1 & 2
cleanDatabaseByMessages
  Deleting attachment entries from 'part' not belonging to remaining mms entries
  Deleting other threads from 'thread'...
updateThreadsEntries
  Dealing with thread id: 1
  Deleting entries from 'mention' not belonging to remaining mms entries
  Deleting removed groups...
  Deleting unneeded MessageSendLog entries...
  Deleting unreferenced recipient entries...
  Deleting unused avatars...
  Deleting unused attachments...
  Delete others from 'identities'
  Deleting group_receipts entries from deleted messages...
  Deleting group_receipts from non-existing recipients
  Deleting drafts from deleted threads...
  Deleting remapped recipients for non existing recipients
  Vacuuming database
1 84236
Switching sms entries...
Unhandled type: 52433 0
2 20263
Switching mms entries...
Unhandled type: 4873 22
Unhandled type: 7182 22
Unhandled type: 9076 22

Exporting backup to 'other-reversed.backup'
Writing HeaderFrame...
Writing DatabaseVersionFrame...
Writing SqlStatementFrame(s)...
  Dealing with table 'part'... 6/8820 entries...Warning: attachment data not found (rowid: 7, uniqueid: 1603042126564)
  Dealing with table 'part'... 286/8820 entries...Warning: attachment data not found (rowid: 289, uniqueid: 1608021908637)
  Dealing with table 'part'... 421/8820 entries...Warning: attachment data not found (rowid: 426, uniqueid: 1610366566528)
  Dealing with table 'part'... 805/8820 entries...Warning: attachment data not found (rowid: 816, uniqueid: 1611583611408)
  Dealing with table 'part'... 4341/8820 entries...Warning: attachment data not found (rowid: 4371, uniqueid: 1623434713373)
  Dealing with table 'part'... 4347/8820 entries...Warning: attachment data not found (rowid: 4377, uniqueid: 1623434749395)
  Dealing with table 'part'... 4354/8820 entries...Warning: attachment data not found (rowid: 4384, uniqueid: 1623435941826)
  Dealing with table 'part'... 4616/8820 entries...Warning: attachment data not found (rowid: 4646, uniqueid: 1624622861781)
  Dealing with table 'part'... 4617/8820 entries...Warning: attachment data not found (rowid: 4647, uniqueid: 1624622861792)
  Dealing with table 'part'... 4830/8820 entries...Warning: attachment data not found (rowid: 4863, uniqueid: 1625415404534)
  Dealing with table 'part'... 6262/8820 entries...Warning: attachment data not found (rowid: 6297, uniqueid: 1628846453449)
  Dealing with table 'part'... 6898/8820 entries...Warning: attachment data not found (rowid: 6933, uniqueid: 1631988590595)
  Dealing with table 'part'... 7753/8820 entries...Warning: attachment data not found (rowid: 7795, uniqueid: 1635451708991)
  Dealing with table 'part'... 8487/8820 entries...Warning: attachment data not found (rowid: 8529, uniqueid: 1639313766933)
  Dealing with table 'part'... 8820/8820 entries...done
  Dealing with table 'drafts'... 0/0 entries...
  Dealing with table 'push'... 0/0 entries...
  Dealing with table 'groups'... 0/0 entries...
  Dealing with table 'recipient'... 2/2 entries...done
  Dealing with table 'group_receipts'... 0/0 entries...
  Dealing with table 'sticker'... 103/103 entries...done
  Dealing with table 'storage_key'... 0/0 entries...
  Dealing with table 'mention'... 0/0 entries...
  Dealing with table 'remapped_recipients'... 0/0 entries...
  Dealing with table 'remapped_threads'... 0/0 entries...
  Dealing with table 'payments'... 0/0 entries...
  Dealing with table 'chat_colors'... 0/0 entries...
  Dealing with table 'sender_key_shared'... 0/0 entries...
  Dealing with table 'pending_retry_receipts'... 0/0 entries...
  Dealing with table 'msl_payload'... 0/0 entries...
  Dealing with table 'msl_recipient'... 0/0 entries...
  Dealing with table 'msl_message'... 0/0 entries...
  Dealing with table 'thread'... 1/1 entries...done
  Dealing with table 'mms'... 20238/20238 entries...done
  Dealing with table 'sms'... 84128/84128 entries...done
  Dealing with table 'avatar_picker'... 0/0 entries...
  Dealing with table 'identities'... 0/0 entries...
  Dealing with table 'group_call_ring'... 0/0 entries...
  Dealing with table 'sender_keys'... 0/0 entries...
  Dealing with table 'reaction'... 100/100 entries...done
  Dealing with table 'notification_profile'... 0/0 entries...
  Dealing with table 'notification_profile_schedule'... 0/0 entries...
  Dealing with table 'notification_profile_allowed_members'... 0/0 entries...
  Dealing with table 'emoji_search'... 0/0 entries...
Writing SharedPrefFrame(s)...
Writing KeyValueFrame(s)...
Writing Avatars...
Writing EndFrame...
Done!
`

What are these "Warning: attachment data not found"? Is it ok?

**Comment by HiperFall** [comment]
Please, answer as soon as possible. My friend is here for two more days.

**Comment by bepaald** [comment]
>What are these "Warning: attachment data not found"? Is it ok?

Yeah that's safe to ignore.

>I restored from the reversed backup, everything is ok, but all messages are marked as "delivered, but not read".
How to make them marked as read? Same with voice messages.

Well, that's good news. Thanks for letting me know. I did indeed forget to mark all outgoing messages as read. To fix you could try (on your last, already reversed beackup):
```
signalbackup-tools other-reversed.backup [passwrd] --runsqlquery "UPDATE sms SET delivery_receipt_count = 1 WHERE (type & 0x1f) IS 23" --runsqlquery "UPDATE mms SET delivery_receipt_count = 1 WHERE (msg_box & 0x1f) IS 23" -o other-reversed-read.backup
```

This is just a quick try, of the top of my head, let me know if it works, otherwise, I'll have to look into it tomorrow.

**Comment by HiperFall** [comment]
I've tried, but it didn't work. The messages are marked as delivered.

**Comment by bepaald** [comment]
O sorry, that was stupid of me. I woke up in the middle of the night thinking 'sh*t I meant _read_ not _delivery_'... So, try this instead:
```
signalbackup-tools other-reversed.backup [passwrd] --runsqlquery "UPDATE sms SET read_receipt_count = 1 WHERE (type & 0x1f) IS 23" --runsqlquery "UPDATE mms SET read_receipt_count = 1 WHERE (msg_box & 0x1f) IS 23" -o other-reversed-read.backup
```

**Comment by HiperFall** [comment]
Thanks a lot!!! It worked perfectly!!!

**Comment by bepaald** [comment]
Excellent, glad it worked!

Now that it's been tested twice, I think I might rename the function and document it in the readme in the near future.

**Comment by apurv3170** [comment]
Thanks man! @HiperFall @umglurf @bepaald 
I appreciate you all helping me out. I did it! I know its been a while but I got what I wanted after I read the whole thread.

**Comment by SimplyMinimal** [comment]
Hi,

I've been asked to help restore a friend's conversation from another backup and this feature is exactly what I need to accomplish this. Running the command without `--setselfid` allows me to extract a single thread but it then re-creates it as "Note to Self". 

However, it seems there's a minor bug now when I use `--setselfid` in an attempt to correct this.

> signalbackup-tools "${DB1}" "${PASSWORD1}" --hiperfall 128 --setselfid "${SELF_PHONE_NUMBER}" --output ${DB2} -op "${PASSWORD2}"
 *** Starting log: 2025-06-16 20:10:45 ***
signalbackup-tools (signalbackup-tools) source version 20250613.154141 (SQLite: 3.49.2, OpenSSL: OpenSSL 3.5.0 8 Apr 2025)
Opening from dir!
Reading database...
Reading HeaderFrame
Reading DatabaseVersionFrame
Reading SharedPreferenceFrame(s)
Reading KeyValueFrame(s)
Reading EndFrame
Reading AvatarFrames: 112/112
Reading AttachmentFrames
Reading StickerFrames
Done!
Database version: 277
[Error]: During sqlite3_prepare_v2(): no such column: phone
         -> Query: "SELECT _id FROM recipient WHERE phone = ?"
[Error]: Some error occurred in SignalBackup::hiperfall()...

Looks like there's been a change in the schema where `phone` should now be `e164`. I see you do not accept pull requests so I'm putting a comment here instead.

**Comment by bepaald** [comment]
>Looks like there's been a change in the schema where phone should now be e164. This is just a guess though from testing around with a few simple SQL queries.

That's a good guess! There was an old hardcoded 'phone' in there, while those should have been switched to the variable version instead. Should be fixed now.

>Running the command without --setselfid allows me to extract a single thread but it then re-creates it as "Note to Self".

I am curious if it is going to fix your problem however. Generally, if the tool should either fail to determine the self-id (and show an error message), or it should succeed (and manually setting `--setselfid` should not be needed or not make a difference).

How are you determining that the messages end up in note-to-self? Are you actually importing DB2 into your friends backup and restoring it, or simply inspecting (for example running `--exporthtml`) on DB2 directly? If I remember correctly, normally DB2 should be imported into a backup from your friends phone to finish the procedure (`signalbackup-tools ${DB3} ${PASSWORD3} --importthreads all -s ${DB2} -sp ${PASSWORD2} -o ${DB4}`). If you just look at DB2 directly, it is expected the messages _appear_ as note-to-self (at least a quick test with `--exporthtml` confirms this).

**Comment by SimplyMinimal** [comment]
Thank you for the quick update! I'll give it a go as soon as I can.

As for the testing, I did both `--exporthtml` and an actual restore to confirm. The actual restore matches how `--exporthtml` looks in that it falls under the Note-To-Self.
