### ISSUE TITLE
Paths on windows not recognized as directory

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#47]
For most parameters forgetting to end the path with a slash will result in a single file, rather than recognizing the path as a directory. Ideally the tool recognizes any output path as a directory regardless of the final slash being omitted.

For the --dumpmedia parameter the slash has to be omitted otherwise the tool throws an error, that's inconsistent with other parameters.

**Comment by bepaald** [comment]
>For most parameters forgetting to end the path with a slash will result in a single file, rather than recognizing the path as a directory. Ideally the tool recognizes any output path as a directory regardless of the final slash being omitted.

Not sure what you mean here. What parameters are you talking about? Most require a file as output (--exportxml), others require a directory (--dumpmedia). The only parameter taking both is --output, and it seems to work just fine? When given a filename it exports to file, when giving a directory it exports to directory.

>For the --dumpmedia parameter the slash has to be omitted otherwise the tool throws an error, that's inconsistent with other parameters.

This is working as far as I can tell. I don't generally test Windows, but I fired up my VM for this specifically.

On linux:
```
[~/programming/signalbackup-tools] $ rm -r test/*
[~/programming/signalbackup-tools] $ ./signalbackup-tools ~/PHONE/DEVsignal-2021-10-10-15-53-01.backup $pwd --dumpmedia test
signalbackup-tools (./signalbackup-tools) source version 20211102.074914 (OpenSSL)
[...]
Reading backup file...
FRAME 632 (100.0%)... Read entire backup file...

done!
Dumping media to dir 'test'
Saving attachments...  31/31
done.
[~/programming/signalbackup-tools] $ rm -r test/*
[~/programming/signalbackup-tools] $ ./signalbackup-tools ~/PHONE/DEVsignal-2021-10-10-15-53-01.backup $pwd --dumpmedia test/
signalbackup-tools (./signalbackup-tools) source version 20211102.074914 (OpenSSL)
[...]
Reading backup file...
FRAME 632 (100.0%)... Read entire backup file...

done!
Dumping media to dir 'test/'
Saving attachments...  31/31
done.
```

And on Windows:
```
S:\>signalbackup-tools_win.exe DEVsignal-2021-10-10-15-53-01.backup $pwd --dumpmedia c:\test\
signalbackup-tools (signalbackup-tools_win.exe) source version 20211102.074914 (OpenSSL)
[...]
Reading backup file...
FRAME 632 (100.0%)... Read entire backup file...

done!
Dumping media to dir 'c:\test\'
Saving attachments...  31/31
done.

S:\>signalbackup-tools_win.exe DEVsignal-2021-10-10-15-53-01.backup $pwd --dumpmedia c:\test
signalbackup-tools (signalbackup-tools_win.exe) source version 20211102.074914 (OpenSSL)
[...]
Reading backup file...
FRAME 632 (100.0%)... Read entire backup file...

done!
Dumping media to dir 'c:\test'
Saving attachments...  31/31
done.
```

Could you show me the output you are seeing?

**Comment by Meteor0id** [comment]
exporting to a file is intentional? I thought it was a bug. Apologies.

**Comment by bepaald** [comment]
>exporting to a file is intentional? I thought it was a bug. Apologies.

Yes, it's actually one of the main features of the program. That way, after editing the backup (for example repairing, merging, cropping), you end up with a new backup file that can actually be imported by the android app.

Thanks for your report!
