### ISSUE TITLE
Suggestion: render styled HTML output mimicing the layout of the app

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#50]
I think it would be great if the HTML export in the future created a index.html which is styled like the Android conversation list, and more HTML files one for each conversation. The styling should be easy to do with some simple CSS.
 Might be able to contribute in the future to write the CSS.

**Comment by bepaald** [comment]
Yes, that's the idea. I've started this a few times, but my HTML skills are not the best so it always goes slowly. Implementing all features is quite difficult (quotes, mentions, reactions, all types of attachments). But it'll happen one day!

If you are in a hurry, you could check out: [https://github.com/GjjvdBurg/signal2html](https://github.com/GjjvdBurg/signal2html), which already does a pretty good job right now.

Thanks!

**Comment by Meteor0id** [comment]
This feature exists, closing this issue. There is an other issue to track enhancements and bug fixes.
