### ISSUE TITLE
Unable to generate backup

### ISSUE THREAD

**Issue by lidderdj** [bepaald/signalbackup-tools#59]
Hi, 

I'm running and have the following result. The signal.backup file is 297mb. The .xml generated contains only header information. 

PS C:\Users\lidde\Downloads\Signal backup> .\signalbackup-tools_win.exe New.backup password --exportxml backup
signalbackup-tools (C:\Users\lidde\Downloads\Signal backup\signalbackup-tools_win.exe) source version 20220218.171943 (OpenSSL)
IV: (hex:) [omitted] (size: 16)
SALT: (hex:)  [omitted] (size: 32)
BACKUPKEY: (hex:)  [omitted] (size: 32)
CIPHERKEY: (hex:)  [omitted] (size: 32)
MACKEY: (hex:)  [omitted] (size: 32)
COUNTER: 540731214
Reading backup file...
FRAME 0 (000.0%)...
WARNING: Bad MAC in frame: theirMac: (hex:) 25 9e 4a c3 2b e6 09 a2 da 2b
                             ourMac: (hex:) 5c 67 c9 5a b6 38 4b 02 89 6e 8e b2 54 4c 4d 09 92 d8 33 69 2d 84 40 cc 5c 23 6f 2b 9e f6 24 38
Failed to get valid frame from decoded data...
Encrypted data had failed verification (Bad MAC)
Starting bruteforcing offset to next valid frame... starting after: 58
Checking offset 311188690 bytesFailed to read 4 bytes from file to get next frame size... (-1 / 311188756)
Failed to read 4 bytes from file to get next frame size... (-1 / 311188756)
Failed to read 4 bytes from file to get next frame size... (-1 / 311188756)

done!
WARNING EndFrame was not read: backup is probably incomplete

Exporting backup to 'backup'
Error executing query: "SELECT protocol,subject,service_center,read,status,date_sent,date,address,type,body,expires_in FROM sms WHERE type != ?"
SQL error during sqlite3_prepare_v2(): no such table: sms

**Comment by bepaald** [comment]
I am 99.9% percent certain you used an incorrect passphrase.

There is technically no way for the program to know the difference between a wrong password and corrupted backup data, but the fact that the first error is encountered at frame 0 makes it likely that the password is wrong. I will try to update the program to issue a warning in this case when I have time. In the meantime, triple check your password, even if you type it correctly, try using it in the Android app, or with any other backup decryptor to verify it is correct and there is a bug in this program.

Let me know, thanks!

**Comment by lidderdj** [comment]
Ahh, thanks so much. It turns out I did have one character wrong. Apologies!

**Comment by bepaald** [comment]
No worries. Thanks for reporting back!
