### ISSUE TITLE
Replacing Signal Sqlite database in backup

### ISSUE THREAD

**Issue by UrmelAusDemEis** [bepaald/signalbackup-tools#64]
Hello everyone,

I have accidentally deleted the signal app from my Android phone. I have no backup of my data but I am still logged in on my desktop. So, I know that there is no way to create a backup from the Desktop-App which is compatible with my Android phone. However, I have still access to all of the messages through the sqlite.db on the Desktop. 

Do you guys know if there is a way to synthesize a backup from the sqlite.db? Maybe there is a way to replace the DB in an existing backup?

Best regards

**Comment by bepaald** [comment]
The database used by the backup and the one used by signal desktop are _vastly_ different, they really do not bear any similarity at all. So, short answer: no. Sorry.

I am actively working on this though. 'Actively' meaning this is the one feature I'm working on when I have time (which is not often) and when I'm not trying to fix current functionality when the backup's format changes (which always gets my priority).

Anyway, I'm afraid even in the most optimistic estimate it will be months before this is ready for the first tests (though I do actually have a couple days off work in a few weeks, which might speed things up).

The good news is, if I ever get this working, it should be possible to import the messages from a desktop installation into an existing backup. So theoretically, you could just start fresh now, and have your old messages prepended to your message history at some later point. Please be sure to keep a backup of your current signal-desktop data folder though!

Also, for reference, see #57

**Comment by UrmelAusDemEis** [comment]
Oh wow, that sounds really promising! Thank you for your work :)

**Comment by bepaald** [comment]
Closing this just for cleanup. #57 is where you can follow progress on this (it's not done yet, but it may be getting close).
