### ISSUE TITLE
Successful merge operation!

### ISSUE THREAD

**Issue by pmelanson** [bepaald/signalbackup-tools#69]
Hey bepaald! Purely informational:

> If you use this option and read this line, I would really appreciate it if you let me know the results.

I recently used the backup merge option successfully! Pasting my commands here, hopefully they will be helpful for future users and bepaald.

Scenario: I foolishly turned on the "delete messages older than 6 months" option in the Signal app, and lost history. My girlfriend still had a complete backup, so I was able to `--hiperfall` her backup and `--croptothreads` to select our conversation (also using `--mergerecipients` to merge two of my old phone numbers). Then, I reconciled our backups with `--importthreads`:

```
$ .\signalbackup-tools_win.exe .\girlfriend.backup [passphrase] --mergerecipients '+my_old_number','+my_new_number' --hiperfall 8 -o merged-and-hiperfall.db

[command successful]
```
```
$ .\signalbackup-tools_win.exe .\merged-and-hiperfall.db [snip] --listthreads

Database version: 146
---------------------------------
| Min Date      | Max Date      |
---------------------------------
| 1625529775797 | 1655516372596 |
---------------------------------
-----------------------------------------------------------------------------------------------------------------------
| _id | recipient_ids | snippet                                                                | Conversation partner |
-----------------------------------------------------------------------------------------------------------------------
| 8   | [snip] | [snip] | [snip] |
-----------------------------------------------------------------------------------------------------------------------
```
```
$ .\signalbackup-tools_win.exe .\signal-2022-06-18-13-55-02.backup [my-passphrase] --importthreads 8 --source .\merged-and-hiperfall.db --sourcepassword [her-passphrase] --output truncatedbackup-and-hiperfallbackup-merged.backup
```

Copied `truncatedbackup-and-hiperfallbackup-merged.backup` and used Signal to restore from the backup, I can now see the messages I lost! There's probably some message duping in the span of time where our backups overlap, but I didn't bother fixing that.

Thanks for the tool (and the paypal link)!

**Comment by bepaald** [comment]
Hi Patrick! Thank you so much for your feedback. I'm very happy everything worked out for you, especially with using the poorly tested and possibly outdated `hiperfall` and `mergerecipients` functions, both in one command no less! If you discover any problems later on, please do let me know.

Thanks again!
