### ISSUE TITLE
Feedback - merge feature

### ISSUE THREAD

**Issue by fakob** [bepaald/signalbackup-tools#71]
Hi @bepaald 
Your tool worked like a charm. Thanks for your work!

As someone who was completely new to this I have 2 comments for things which were not completely clear to me. This might help others who are as newbie as I was:

* When creating a chat backup from the app, one is presented with passphrase which is the equivalent of the password required in your command. The numbers have to be written without spaces
  * E.g. 01234 56789 01234 56789 01234 56789 -> 012345678901234567890123456789
* It is mandatory to set a password/passphrase for the merged file. This password needs to be a number with 30 digits. Otherwise restoring the merged backup onto a new phone does not work. At least that was my experience.

Hope it helps :-)

**Comment by bepaald** [comment]
Thanks for your feedback! About you notes:

- The numbers don't actually have to be written without spaces, it's just that your command line interpreter assumes things separated by spaces are different tokens. If you put quotes around the passphrase, it recognizes it as a single token and my program should handle that fine. As an alternative, any other character is actually allowed in the passphrase as long as it contains exactly 30 digits. Examples:
```
./signalbackup-tools signal-2022-07-24-12-00-00.backup 012345678901234567890123456789        # OK
./signalbackup-tools signal-2022-07-24-12-00-00.backup "01234 56789 01234 56789 01234 56789" # OK
./signalbackup-tools signal-2022-07-24-12-00-00.backup 01234.56789.01234.56789.01234.56789   # OK
```

- Not sure what you mean. The backup file indeed has to have a passphrase, and that has to be 30 digits. This is required by Signal, though I could indeed mention that somewhere in the readme and/or the `--help` function. But it should not be mandatory to manually set a new passphrase: if ommitted, the input-passphrase is simply used as output-passphrase. Are you saying if you don't specify the `-op/--opassword` option, the resulting backup can not be restored by Signal? What is the error you're seeing when you try?

Thanks again!

**Comment by fakob** [comment]
Thanks for explaining the different ways to write the numbers!

Regarding the passphrase. I think I misunderstood.
* I assumed that when you merge backupA and backupB, it creates an independent new backupC file
  * which does not have a password unless you set one
* If I understood correctly, what is actually happening, you merge backupB into backupA
  * therefore backupA's password is still valid unless you set a new one

**Comment by bepaald** [comment]
>If I understood correctly, what is actually happening, you merge backupB into backupA
>therefore backupA's password is still valid unless you set a new one

Yes, this is exactly it! Maybe I should make it more clear in the readme.

Thanks again for the feedback. The merge-option breaks occasionally due to changes in Signal, so it's very nice to hear it's currently still working!

If you need any more help, let me know.
