### ISSUE TITLE
hide passwords from commandlines

### ISSUE THREAD

**Issue by GfEW** [bepaald/signalbackup-tools#72]
Although one might argue that signalbackup-tools is only sane to be used in a dedicated airgapped system anyway, providing secrets as commandline arguments is extremely unsafe. Not only will the entire commandline, including its PASSWORD argument, be saved in the current user's shell command history with most default setups, but it is readable even by other users with basic tools like ps or top.

Therefore, I suggest signalbackup-tools to employ a safe default input method for all secrets.

**Comment by bepaald** [comment]
Thanks for your suggestion, I suppose you're mostly right. Though I think 'a dedicated airgapped system' is probably a bit exaggerated for most people. The (extremely small) group of people who are actually targets of powerful agencies and whose lives depend on their messages remaining secret, should definitely be using disappearing messages and have backups disabled (besides, their phones will be the main targets anyway). Any normal person who has something to hide from people he shares his computer with should make sure his files are not readable to others by setting proper permissions on the backup file itself.

Still, it's a nice feature to have and it can't hurt. And maybe there is some niche group who really need it indeed, so I tried to implement something today. The Windows version gave me a real headache, but hopefully it's all working. Give it a try: simply omit the password (or run with `--interactive`) to be prompted for passwords (for input, output and source, as required).

Let me know if this works for you, or if I need to change something. Thanks again!

**Comment by bepaald** [comment]
Assuming this is fixed. Let me know if you have more feedback. Thanks!
