### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by xplosionmind** [bepaald/signalbackup-tools#79]
It would be super useful to have a Homebrew package for this app

**Comment by bepaald** [comment]
I agree it would be nice. And I don't actually think it will be too difficult, but since I don't have any Apple hardware I'm probably not going to do this. Is it possible to test a brew on a non-Apple system?

**Comment by bepaald** [comment]
@xplosionmind and any future readers:

There is a first attempt at a homebrew package now. It's not in any official homebrew package source (yet), but if you download the file https://github.com/bepaald/signalbackup-tools/blob/master/homebrew/signalbackup-tools.rb, you should be able to install with `brew install --HEAD [path/to/signalbackup-tools.rb]` (on somewhat recent versions of macOS).

The README will be updated at a later point.
