### ISSUE TITLE
EndFrame was not read - Framesize too big to be real - No messages, only media

### ISSUE THREAD

**Issue by knoxell** [bepaald/signalbackup-tools#80]
Hey!

Thanks for putting so much effort into this tool, that's really amazing! My Backup (3.5 GB) is from August and the only one I have :-(

My log is [here (pastebin)](https://pastebin.com/PNvnsfjv) (cut a few brutforcing efforts out to shorten it, all with good frame..)

I tried to summarize the problem:

- After running `signalbackups-tools signal.backup pw -o NEWBACKUPFILE -op pw ` all tables are empty, except for `mms`, with 17 entries.
  - `Dealing with table '****'... 0/0 entries...`
  - `Dealing with table 'mms'... 17/17 entries...`
- with `--stoponerror --dumpmedia ../media` I got 3718 media items 
  - without `--stoponerror` I get 3836 items (only 18 lost items from 3836, thats good!)
- `--ashmorgan` says
  - `COUNTER: 3135795142`
  - `Last 100 bytes: (hex:) [not zero]`
  - `Getting frame at filepos: 3699531760`
  - `Framesize too big to be real` 

```log
FRAME 114447 (100.0%)... Failed to read next frame (452 bytes at filepos 3699531650)
Starting bruteforcing offset to next valid frame... starting after: 3699531650
Checking offset 120 bytesFailed to read 4 bytes from file to get next frame size... (-1 / 3699531776)
Failed to read 4 bytes from file to get next frame size... (-1 / 3699531776)
Failed to read 4 bytes from file to get next frame size... (-1 / 3699531776)

done!
WARNING EndFrame was not read: backup is probably incomplete

Exporting backup to 'NEWBACKUPFILE'
```

I'd really appreciate your help, thanks in advance for even looking at this :-)

**Comment by bepaald** [comment]
Hi! I'm sorry to be the bearer of bad news, but I think it is what it is. I see nothing in the log that gives me any new ideas to try for data recovery. Everything I've come up with over the years is already implemented in program, and it is pretty thorough in trying to recover from corrupted data.

Sometimes, a backup is corrupted in a way that the app does not restore it, but all messages are still in the database. These are the cases where I can make some custom function to create a working backup from the data still recovered (usually missing many attachments), but in your case only (most of) the attachments are found, and no message data is present. This is an unfortunat side effect of the order of the data in the backup these days (I've posted about that on Signal's forums [here](https://community.signalusers.org/t/change-order-of-data-in-backup-file-to-make-it-more-resilient-to-errors/35795), but without any effect so far).

So, I don't think there is anything I can do to help more than the attachments already recovered by the program, but please let me know if you think I can help with anything else.

**Comment by knoxell** [comment]
Thank you so much for looking over the logs!
Too bad, there (probably) is noting to be done about it :(

I guess when I find some time, I'll have to look into the ['Generate an Android backup from the Desktop app' Issue](https://github.com/bepaald/signalbackup-tools/issues/57). Though it seems very overwhelming to me.
