### ISSUE TITLE
Future plan: add graphical user interface

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#81]
Not a high priority (lower than import from desktop and export as HTML) but I think this tool could be of use to many more people if it also featured a GUI.

Although command line interfacing works fine, there are many Signal users who would be intimidated by any command line tool, but would love to export their chats to readable achievable formats.

Just something to consider for the future.

**Comment by bepaald** [comment]
Yeah, I'll leave this open, I've thought about this often and realize it would be nice for a lot of people. So maybe in the future.

I think it would be very hard to make the GUI a nice user experience with this particular program, but for some maybe still better than the CLI.

I have tried hard to keep dependencies small for this program, also to help keep it cross-platform. A GUI would make this a bit more difficult, so it should probably be a separate program calling this one in the background.

<details>
  <summary>spoiler</summary>
  <p>
If I had all the money in the world and quit my job I'd make something nice and integrate it with the half finished GUI backup-viewer I wrote years ago ;-) that would really be cool

![screenshot3](https://user-images.githubusercontent.com/38437099/206648765-f768fe9e-1f89-4057-a414-12213c5fc574.png)

  </p>
</details>

**Comment by bepaald** [comment]
This was always a long shot, but given the backup situation I'm going to close this. Even if I would start on this now (which I'm not even considering), there is no way this is ever going to be close to working before this entire tool is obsolete (due to BackupsV2).

**Comment by Meteor0id** [comment]
What is backupsv2 and will it realky make this tool obsolete?

**Comment by bepaald** [comment]
Well, I basically don't know. For a while now, in the Backup directory of Signal Androids source tree, there is a folder named `v2` ([here](https://github.com/signalapp/Signal-Android/tree/main/app/src/main/java/org/thoughtcrime/securesms/backup/v2)). It seems the entire backup is being re-implemented. I don't think the switch is imminent, but lately I've seen (closed) backup issues on Signal's github, having responses reading (not a literal quote) "we are looking in to this but with the new v2 backup format that's coming up really what's the point". Which makes me think it's not too far off. Certainly less far than a GUI for this program.

As for what it means for this program, I'm not sure, I've only glanced at the new code for a minute or so, and obviously I don't have a new backup file to do anything with (I don't think anybody does, the new format is not finished I think).

Best case scenario: the core of this program would need to be completely rewritten, to be able to read and write the new backups, but once that works the actual contents are the same and the same functions will work on them (almost) unaltered.

I fully intend to attempt to support the new backups (in this tool, or in signalbackup-tools2), but there's always the possibility that it's too complicated for me. If not, depending on how much time I have (an hour each weekend or a whole month vacation) getting something working could take anywhere from a few weeks to more than a year.

Assuming the new backup format is completely incompatible with the current format, this tool would probably quickly become obsolete as the old format will phase out fairly quickly I think.

Anyway, almost everything above is speculation, I have no inside knowledge, do not take anything as fact.
