### ISSUE TITLE
Suggestion: Use "passphrase" instead of "password" in the readme

### ISSUE THREAD

**Issue by dmlls** [bepaald/signalbackup-tools#82]
First of all, thanks for this nifty tool!

I wanted to suggest replacing the term "password" with "passphrase" in the readme, since this can be confused with the Signal PIN.

I know this is kind of obvious, but I just spent quite some time trying to decrypt the backup with my Signal PIN (in my case is alphanumeric, so it's more of a password than a PIN), getting a misleading `Aborted! (core dumped)` message.

Had the readme said "passphrase" (which is the term used on the app) I would've never made this silly mistake 😅

**Comment by dmlls** [comment]
Thanks for the prompt reply!


The password used had 35 characters and was similar to the following:
`d&*CY$!%&5ireIJlnhjq3Fq5m!ld0!34^RB`


The output I get using the latest signalbackup-tools version `20221222` (installed from Arch AUR) is:
```console
$ signalbackup-tools signal-2022-12-22-15-13-41.backup --output temp
signalbackup-tools (signalbackup-tools) source version 20221222.161452 (OpenSSL)
Please provide passphrase for input file 'signal-2022-12-22-15-13-41_all-media.backup': ***********************************
/usr/include/c++/12.2.0/bits/basic_string.h:1201: constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
```

When I directly pass the password I get the following:
```console
$ signalbackup-tools signal-2022-12-22-15-13-41_all-media.backup d&*CY$!%&5ireIJlnhjq3Fq5m!ld0!34^RB --output temp
bash: !ld0!34: event not found
```

In that case bash seems to complain about the `!`. which I guess should be escaped, but I'm not sure how to achieve this (I tried quoting the password and using `\!` but neither of them worked).

**Comment by bepaald** [comment]
Thanks for reporting back. I'm not at home at the moment but at least I know what to test now, I'll get on it as soon as I have some time.

At least that second case you mention is not a problem in the program but a bash thing (as you already mention), there are more characters that need to be escaped in your example passphrase (at least `*&$!`, but maybe you have another set in the real one). Don't ask me how though. Of course it's possible after properly escaping the abort happens all the same. But that is something I should fix as soon as I have some time.

Thanks again! I'll report back when I have updates.

**Comment by bepaald** [comment]
Was the 'Aborted'-output you posted with the example passphrase or your _actual_ passphrase? I'm trying to reproduce this, but everything seems to work ok:
```
[~/programming/signalbackup-tools] $ ./signalbackup-tools ~/PHONE/DEVsignal-2022-12-14-14-33-16.backup --listthreads
signalbackup-tools (./signalbackup-tools) source version 20221222.161452 (OpenSSL)
Please provide passphrase for input file '/home/svandijk/PHONE/DEVsignal-2022-12-14-14-33-16.backup': ***********************************
ERROR : Failed to parse passphrase from string 'd&*CY$!%&5ireIJlnhjq3Fq5m!ld0!34^RB' : passphrase too short! Need 30 digits, 7 provided
Error: Failed to get backupkey from passphrase
Failed to create filedecrypter
Failed to open backup
```

I then added every special character I could think of and some 2- and 3-byte UTF characters, but it all just keeps working. Do you get the same error with other passphrases? Maybe, if it's not too much trouble, you could try a few variations with only select few special characters to see if any one of them in particular is giving problems. Not sure what to do here right now...

**Comment by dmlls** [comment]
> Was the 'Aborted'-output you posted with the example passphrase or your _actual_ passphrase? I'm trying to reproduce this, but everything seems to work ok:

Actually both 😅 

> I then added every special character I could think of and some 2- and 3-byte UTF characters, but it all just keeps working. Do you get the same error with other passphrases?

I've tried even just with letters and it shows the same error.

---

**Update**: I've tried compiling from source with `g++ -std=c++2a */*.cc *.cc -lcrypto -lsqlite3` and then I get the expected behavior!
```console
ERROR : Failed to parse passphrase from string 'd&*CY$!%&5ireIJlnhjq3Fq5m!ld0!34^RB' : passphrase too short! Need 30 digits, 7 provided
Error: Failed to get backupkey from passphrase
Failed to create filedecrypter
Failed to open backup
```

I see the AUR [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=signalbackup-tools-git) uses the script [`BUILDSCRIPT_MULTIPROC.bash44`](https://github.com/bepaald/signalbackup-tools/blob/master/BUILDSCRIPT_MULTIPROC.bash44). Could it be there's something wrong in there?

**Comment by bepaald** [comment]
Hmm, could you try using it to build and see if the problem occurs?

The options in the build script are the default options I use myself, they should be good. Also, building from AUR works for me, but when I did that, I did notice that (contrary to when running the script directly) when building from AUR, the flags (`CXXFLAGS` and the likes) are taken from `/etc/makepkg.conf`, maybe those are messing up the build? They don't on my machine, but maybe on yours? I should still probably do something about that though.

**Comment by dmlls** [comment]
> Hmm, could you try using it to build and see if the problem occurs?

Okay, so building directly with the script also works as expected.



> The options in the build script are the default options I use myself, they should be good. Also, building from AUR works for me, but when I did that, I did notice that (contrary to when running the script directly) when building from AUR, the flags (`CXXFLAGS` and the likes) are taken from `/etc/makepkg.conf`, maybe those are messing up the build? They don't on my machine, but maybe on yours? I should still probably do something about that though.

Could well be. So this is the arguments passed to `g++` when I directly run the script:
```console
g++ -c -Wall -Wextra -Wshadow -Wold-style-cast -Woverloaded-virtual -pedantic -O3 -flto  -march=native -std=c++2a signalbackup/importwachat.cc -o signalbackup/o/importwachat.o
```
versus the one when bulding from the AUR:
```console
g++ -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS  -march=native -std=c++2a signalbackup/importwachat.cc -o signalbackup/o/importwachat.o
```

<br>

The args in the first command not present in the second are:
```console
'-O3', '-Wall', '-Wextra', '-Wold-style-cast', '-Woverloaded-virtual', '-Wshadow', '-flto', '-pedantic'
```

and the args in the second not in the first:
```console
'-O2', '-Werror=format-security', '-Wformat', '-Wp,-D_FORTIFY_SOURCE=2', '-Wp,-D_GLIBCXX_ASSERTIONS', '-fcf-protection', '-fexceptions', '-fno-plt', '-fstack-clash-protection', '-march=x86-64', '-mtune=generic', '-pipe'
```

Hope that helps!

**Comment by bepaald** [comment]
Thanks for your thorough investigation! I was able to reproduce it, now I can more easily try to find the exact cause. I'll report back here.

**Comment by bepaald** [comment]
Thanks again. this turned out to be an ugly, shameful logic error in my code which has lived there since forever. You were the first to find it, congrats!

Anyway I think I fixed it (I hope). Maybe you could test just to be sure? Any compiler options should work, but building from AUR would be the best way to check in your case I think.

Thanks again!

**Comment by dmlls** [comment]
Works beautifully!

Thank YOU! :)
