### ISSUE TITLE
Database Merge Error "--opassphrase': Unknown option."

### ISSUE THREAD

**Issue by MtaTech** [bepaald/signalbackup-tools#86]
Sorry my fault :) Remove `(` `)` and fix.

Hello, I want to merge two databases. I get this error.

`signalbackup-tools_win.exe [C:\Signal\Backups\signal-2018-06-12-04-10-03.backup] [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx] --importthreads ALL --source [C:\Signal\Backups\signal-2018-09-26-01-25-15.backup] --sourcepassphrase [yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy] --output [signalmerge201806-201809.backup] (-op [cccccccccccccccccccccccccccccc])`

- `[ Error parsing command line option `(--opassphrase': Unknown option. ]`

- `[ Error parsing command line option `(-op': Unknown option. ]`

**Comment by bepaald** [comment]
Hi! Thanks for your report. Please make sure you are using the latest, current version of the program, the 'passphrase' options are a somewhat recent addition (they were called 'password' before).

As far as I can tell the option is parsed (here https://github.com/bepaald/signalbackup-tools/blob/bc2bd8df224a294c39537680cd70a36bf2ad61f2/arg/arg.cc#L215), but please let me know if you're already using the latest version or still see this issue after updating. I'm not at home right now but will look into it tomorrow.

I am very curious to hear whether merging works correctly. It has been working well for a while, but huge database changes have been happening recently so please let me know. Also, make sure to have both your backups fully updated (or both of them somewhat old): trying to merge an older database (pre v170) with a new one (>= 170) is sure to cause problems.

Thanks again, let me know if you need more help.

**Comment by bepaald** [comment]
O sorry, I only just read your edit. I take it this problem is fixed? Also, looking at the dates of the backup files, merging should work OK.

Let me know if there is anything else, or feel free to close this issue if everything is fine. Thanks!

**Comment by MtaTech** [comment]
> But please let me know if you're already using the latest version or still see this issue after updating. I'm not at home right now but will look into it tomorrow.
> I am very curious to hear whether merging works correctly. It has been working well for a while, but huge database changes have been happening recently so please let me know. Also, make sure to have both your backups fully updated (or both of them somewhat old): trying to merge an older database (pre v170) with a new one (>= 170) is sure to cause problems.
> 
> Thanks again, let me know if you need more help.

2017-2018-2019
I merged the files from these years. I have a question. If 2 different backups have the same message, does it overwrite it? Or double entry?
You did a really great thing. thank you so much. Is there a way to use "gpu" when decrypting?
(Sorry for the bad spelling. I'm using a translation app.)

**Comment by bepaald** [comment]
The merge function will just merge. To prevent double messages, you can either use `--croptodates` to crop one of the backups to a smaller time frame, or `--removedoubles` to try and remove the doubled messages.

There is no GPU acceleration, but from my experience the decrypting is often faster than the file can be read from disk, so it wouldn't be much use.

Thanks!
