### ISSUE TITLE
look for config and database at signal beta path

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#90]
I am getting the following output:
```

Reading backup file...
FRAME 28618 (100.0%... Read entire backup file...

done!

WARNING Foreign key constraint violated.
-----------------------------------------
| table | parent | fkid |
-----------------------------------------
| msl_recipient | msl_payload | 0 |
| msl_message | msl_payload | 0 |
-----------------------------------------
Failed to open input: C:\Users\myusername/AppData/Roaming/Signal/config.json
Error : Failed to open database
```
note that i am using the signal desktop beta app, turns out I have to
--importfromdesktop "C:\Users\myusername\AppData\Roaming\Signal Beta" "C:\Users\myusername\AppData\Roaming\Signal Beta"

Maybe this could be a default location to check for?

**Comment by bepaald** [comment]
Thanks! Should be fixed now... I'll close this now, but please let me know if it's still a problem.

Note by the way, the `WARNING Foreign key constraint violated` has nothing to do with this, and is a problem in the Android backup. You might be running into https://github.com/signalapp/Signal-Android/issues/12703.
