### ISSUE TITLE
feature request: render index.html as interactive conversation list

### ISSUE THREAD

**Issue by Meteor0id** [bepaald/signalbackup-tools#92]
currently the tool can export individual chats as html/css. Would be nice if the tool would also render an index html to show the conversation list, with clickable entries and a back button on each chat to return to the index This would make the output easier to browse.

**Comment by bepaald** [comment]
Yes, excellent idea. I'll get on this when I have some time, hopefully this weekend. Thanks!

**Comment by bepaald** [comment]
The `--exporthtml` function now outputs a `index.html` file. It is a fairly quick hack, I consider it a work-in-progress that will probably be tweaked very slowly for a long time. But please let me know if this works for you and if you see any major issues.

Thanks!
